### ISSUE TITLE
Changing the game title text in the Title screen

### ISSUE THREAD

**Issue by erwinsonbp** [07th-mod/umineko-question#100]
I've patched my copy of the question arcs and answer arcs with the voice and graphics patch and noticed that the game title text in the Question arcs is in Japanese while the one in the Answer arcs is in English.

Here's a screenshot: 

![umineko_ when the seagulls cry 06_18_2018 2_36_40 pm](https://user-images.githubusercontent.com/8281524/41521682-b3b67d1a-7305-11e8-80e3-a3a1038711ab.png)
![umineko_ when the seagulls cry chiru 06_18_2018 2_37_32 pm](https://user-images.githubusercontent.com/8281524/41521730-e2479c9a-7305-11e8-9730-56beea3f12ce.png)

I do not know if they were like that from the start when I installed the game or if the patch affected it, and I can't re-install the two games because I'm connected on a metered network. Also, I only did a manual patching of the games (I downloaded the patches from a different PC connected on a non-metered network) and patched the game myself, so I can't tell for sure if I messed something up or not.

Did I messed up patching it?

If this was intentional though, is there anywhere I can get (I'm assuming a sprite) of the Question arcs' title in English? Or if this was intended but will be fixed later, then I'll just wait for it. Thanks.

**Comment by drojf** [comment]
I'm pretty sure you patched it OK, it's just the question arcs logo hasn't been updated yet. I've asked in the discord about it since I think someone has already made a logo, we just need to put it in. 

Don't close this thread - I'll use it to follow up on the logo fix.

**Comment by erwinsonbp** [comment]
Glad that it was just the case. I was thinking though if it will be added here in the repo or will it be added in the CG/sprites/updates archives because I want to get it as soon as it's updated, but I will probably see it when this issue is closed anyway. Thanks.

**Comment by drojf** [comment]
The repo only hosts script updates, so we would just update the 'update file' on the wiki.

However it turns out we might push a script update due to some related issue with transparent images. This means you'll need a script update and an asset update. but yea, will keep you updated.

**Comment by drojf** [comment]
I just pushed the changes for this. You can download the new script and new update pack here: (just overwrite existing files. Make sure to extract to the root of the game directory).

You want the first column (the 0.utf file (remember to rename to 0.u)) and the last column (Update v5.zip)

https://github.com/07th-mod/guide/wiki/Umineko-Part-1---Voice-and-Graphics-Patch#manual-installation-windowslinuxmac 

Let me know if anything to do with that logo image looks wrong (it appears during the 'eyecatch' sections of the game)
