### ISSUE TITLE
Opening Videos are too spoilery

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-question#101]
It was discussed on discord that the opening videos that we added in (the PS3 OPs) for Episodes 1-3 are too spoilery. I've opened this thread to discuss this topic.

Possible options
- Use the old/original opening video (we need to fix the aspect ratio, can't use it as-is)
- Fort mentioned that he had made an OP video which is less spoilery. I'm sure some may be against using custom content in the patch, but it's probably better than using the original opening video, as the art styles differ too much. Personally I think this is a good option.
- Give the user some option to use the new/old openings?
- ?? any suggestions?

Just a refresher: Episodes 1-3 uses "[umineko_op.mpg yt link](https://www.youtube.com/watch?v=HA0BCfgypgQ&t=17s)", and Episode 4 uses "[umineko_op3.mpg  yt link](https://www.youtube.com/watch?v=hU_vECs4i10)" 

If we're going to re-do the video files, we could possibly fix the video scale as well (the game upscales videos 2x by default, but I patched the .exe for Chiru to make it render at 1x scale). It may be a good idea to just render the video at different resolutions so it's easy to change in the future (1080p, 960p, and 480p). I should still have the ffmpeg command I used last time, if you're having trouble getting the game to play your video.

**Comment by irlPM** [comment]
I feel the same as Italo, it's certain that if we change the opening a lot of people will be mad too. There is no winning to this :(

**Comment by drojf** [comment]
yea it's pretty easy to add it in actually. I can make it ask you the first time you open the game with the patch, but if you change your mind you can change it from the settings menu.

**Comment by drojf** [comment]
Not sure about the wording on the text. Also, should I block the ep1-3 video only or ep4 as well? 

![stuff](https://user-images.githubusercontent.com/1249449/42753532-9d8db536-8934-11e8-9c90-e213bc380602.PNG)

**Comment by ItaloKnox** [comment]
The message looks fine. I would remove the "spoilery" from the choice and just leave it as ``Play PS3 Movies``, it's redundant since the text before explains that the PS3 openings may contain spoilers.

**Comment by drojf** [comment]
Reopening to consider alternate opening videos

**Comment by ZahnPastor** [comment]
also i just redownloaded a fresh install of umineko + patched it with the new 1080p version, and i never got this dialog to choose a movie option, i only got the one page about the volume options and i think a second page about the 1080p stuff? so this needs to be re-added to the 1080p versions of the script

**Comment by drojf** [comment]
For the 1080p arcs, I decided to use the forteisimo's re-make of the original game's opening, since it solves both the problem of spoilers and having the opening look the same as the original game.

however, you're right, i guess I should also have the option to show the ps3 opening video we were using before.

**Comment by drojf** [comment]
this should be fixed now, although the wiki (for manual install only) hasn't refreshed yet

**Comment by ItaloKnox** [comment]
@drojf I changed the server to update the wiki more often, now it should be refreshed every 30 minutes. I'll keep an eye on it to see if we can go lower, but I hardly believe we can get it in real time without a CPU upgrade.

**Comment by drojf** [comment]
- the 1080p arcs can switch which opening to use (and we ask the user the first time the game runs)
- wiki has been fixed
