### ISSUE TITLE
Can't download patches (0.utf)

### ISSUE THREAD

**Issue by uminomukouni** [07th-mod/umineko-question#102]
Hi and thank you to everyone working on this amazing project!

The problem is when I try to do manual installation and click on the download link for the patches (0.utf) for both answer and question, they don't download, but take me to a different page with lots of text (so I take it the file just opens in my browser). So I want to ask if there is something wrong with the download links or if not how I'm supposed to download it?

**Comment by drojf** [comment]
Hi yea this is a known problem with most internet browsers, try right clicking the link and clicking "save as".

If anyone seeing this issue knows some trick to bypass this, let me know.

**Comment by uminomukouni** [comment]
Thank you x)

**Comment by drojf** [comment]
Hi, sorry I seem to have missed your reply otherwise I would have replied earlier :S

Is there a reason you're doing the manual install? are you on windows or mac?

**Comment by uminomukouni** [comment]
Hi, you probably didn't see because I edited an earlier reply. 

I'm using windows. I tried manual installation because it worked fine when I did it for the question arcs a couple of years ago, and because I read that it had a higher chance of working, I think.

**Comment by ItaloKnox** [comment]
Hey, can you try to install a download manager? Even if temporary. I would recommend [FDM](https://freedownloadmanager.org/), but it can be any you want.

Just copying the patch link and adding it manually in the manager will download the file as intended.

**Comment by drojf** [comment]
> I tried manual installation because it worked fine when I did it for the question arcs a couple of years ago, and because I read that it had a higher chance of working, I think.

If i'm understanding you correctly, you don't mind using the automatic installer? I would recommend using the installer. You can even prevent yourself from re-downloading if you still have the archive files - just put them in a folder called "temp" in the game directory and the installer should recognize them.

For example, put them at the location `C:\Program Files\Steam\Steamapps\common\Umineko\temp` it should recognize it (I hope I got the path correct).

You can download the installer here: https://github.com/07th-mod/guide/wiki/Umineko-Part-1---Voice-and-Graphics-Patch#installer-windows-only

If you still want to install manually, following Italo's instructions is a good idea.

**Comment by uminomukouni** [comment]
I tried using the installer and it worked, YAY! Many thanks to you both for helping me out! ^-^

**Comment by drojf** [comment]
I think this is solved now
