### ISSUE TITLE
On first boot, if you select Japanese language, you can't advance the game (question and answer arcs)

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-question#104]
When you select japanese language, then move on to the 'firstt boot' screens, there is no japanese text to display (or rather the 'continue' button won't show up), so the game will just get stuck.

We should stop you from selecting japanese language at all since it's not supported (users can use the old 'japanese' script for the Question Arcs, but it's not maintained). 

I guess the other fix is to get japanese mode to work, but that would that a lot of effort...

**Comment by drojf** [comment]
This is now 'fixed' - see https://github.com/07th-mod/umineko-question/commit/eec7b48895334da8dfa1006d39a7c8a23ec3841e. Since japanese support is nearly ready, I won't remove the japanese selection screen on the first game startup (i tested it and it seems to work fine now after making the 'only-once-setup' text not specific to english mode).

**Comment by drojf** [comment]
Japanese support has been added to mainline, but not to the "voices only" scripts or "ADV mode scripts", otherwise this issue could be closed.

**Comment by drojf** [comment]
It would be a good idea to remove the Japanese option (both the first startup prompt and the in-game toggle) altogether from these scripts as they don't work properly:

- Question arcs Voice Only
- Answer arcs Voice Only
- Answer arcs ADV mode

O[A]: 
> I think that could be done however you'd also need to disable the one on first startup or else the user will end up stuck with an unusable game if they choose Japanese initially

**Comment by ooa113y** [comment]
The language selector has been removed from the aforementioned scripts.
