### ISSUE TITLE
Voicedelay commands is not working on Japanese mode.

### ISSUE THREAD

**Issue by eigoninaritai-naokichi** [07th-mod/umineko-question#105]
On Japanese mode, many voicedelay commands is not set like this:

`langjp:dwave_jp 0, but_1e79:^^!d900……船……。」\
langen:voicedelay 4480:dwave_eng 0, but_1e79:^......the boat......"^\`

In this case, langjp has to have `:voicedelay 4480`.

Since there are voicedelay that is not set, a scripter has to set the command.

**Comment by drojf** [comment]
Voicedelays are now inserted automagically by VoicesPuter
