### ISSUE TITLE
Links in scripts/installers not updated

### ISSUE THREAD

**Issue by zweiz** [07th-mod/umineko-question#108]
Hi,

It would appear that the links contained in the scripts and installers have not been updated, and return to the old https://github.com links for the resources (which have been 404'd) instead of the new https://07th-mod.com links. (eg: https://github.com/07th-mod/resources/releases/download/Beato/Umineko-Graphics.zip.001 instead of https://07th-mod.com/Beato/Umineko-Graphics.zip.001), as seen in here: https://raw.githubusercontent.com/07th-mod/resources/master/umineko-question/install.sh

Could you update these?

Thank you.

**Comment by drojf** [comment]
ah thanks for telling us, yea we'll update them asap

**Comment by zweiz** [comment]
Thank you. What about the Windows exacutable installers? I believe they have the same issue.

**Comment by ItaloKnox** [comment]
I'm pretty sure only the Unix users got the short end of the stick (as always). We worked on changing the installers right after the server was online.

**Comment by zweiz** [comment]
Alright, thank you.
