### ISSUE TITLE
Alternative way to download the files for a manual install.

### ISSUE THREAD

**Issue by erintesden** [07th-mod/umineko-question#110]
Im having problems to use the installer exe. It just stops suddenly just a while after starting. 

But even if i hadnt that problem, i was late to notice the size of all the files needed for the installation.
They are too heavy for lower internet connections, that is my case.

I just wanted to know, if it could be a possibility to add some kind of mirror with the patch files in a torrent, or a uploading site that permits to continue downloads, like MEGA, using MEGAsync.

**Comment by ItaloKnox** [comment]
Hi,

If you check our [wiki](http://07th-mod.com/wiki/Umineko/Umineko-Part-1---Voice-and-Graphics-Patch/#manual-installation-windowslinuxmac) you will notice we have individual links up for download directly from our server. They should support resuming if you use a download manager.

**Comment by drojf** [comment]
@erintesden just out of curosity, did you go to our 07th-mod.com website, then click the 'get our installer', or did you visit the Wiki page first?

I'm worried people just go straight to the installer page without seeing the wiki/general information. Maybe I can backlink from the installer download page to the wiki.

**Comment by drojf** [comment]
I think this issue is resolved now - the installer itself supports resuming, and the manual download links also support resuming.
