### ISSUE TITLE
System0.ogg censored due to st*r tr*k (both question and answer arcs)

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-question#111]
Replace with original .ogg from original game with star trek quote

**Comment by ZahnPastor** [comment]
speaking of replacing sound files, i seems like kuina.ogg also is bugged, around the 1:00 mark, where it skips/goes silent for a while (playing from a music player anyway, havent gotten to that point in the VN with the patch). I had this problem on my previous computer, and on my new one too, so i assume all people are affected by this. Can you check your version?

**Comment by drojf** [comment]
@ZahnPastor sorry I didn't reply to you until now. I listened from :55 to 1:05 and the song seems to be fine on my computer.

**Comment by drojf** [comment]
@ZahnPastor  I'm going to close this issue - if you still have the issue with kuina.ogg, please send us the file you have (on Discord or otherwise) to check if it's bugged or not as I couldn't reporduce it. You can open a new issue specific to that audio problem too.
