### ISSUE TITLE
Question Arc 1080p Wrong texture placement/size

### ISSUE THREAD

**Issue by Xorboth** [07th-mod/umineko-question#114]
I tried the 1080p beta and spotted a few textures misplaced (or is it just the wrong size?).

1. Black texture doesn't cover the entire screen
Screenshot:
![1](https://user-images.githubusercontent.com/45687969/50347723-ea5f5580-0536-11e9-885c-040bf2045f13.png)

**fixed**

2. Wrong texture placement/size
Screenshots:
![3](https://user-images.githubusercontent.com/45687969/50347745-03680680-0537-11e9-9ac1-9decbfecf83c.png)
![4](https://user-images.githubusercontent.com/45687969/50347748-07942400-0537-11e9-97f5-9c90789ec449.png)

**fixed the eyecatch pattern/ribbon for all eyecatches, but the clock positions would need a script to automatically fix all the clock positions in the entire script, and possibly a re-check, i'm not sure the clocks were correctly positioned in our original patch.**

3. I'm not sure if it happens on 1080p version only, but there's no new line in this string: "game.You"
![5](https://user-images.githubusercontent.com/45687969/50347949-b59fce00-0537-11e9-98f7-7b97f1f24bbb.png)

**fixed**

**Comment by drojf** [comment]
I'll add some other reported issues to this thread

The image "en\bmp\r_click\text\cha\ep2\geo_2.png" has a typo it - it says "wouldVe" instead of "would've". I only checked 1080p but assume it's broken for the normal question arcs as well.

**Comment by drojf** [comment]
I fixed a bug whenever the zooming effect is used just now in https://github.com/07th-mod/umineko-question/commit/27bd8566e604f63c6a61e9a26aca9ff32e77c2b3 . Just a heads up if anyone is still using the old script because you will definitely see this bug.

**Comment by DogLover314** [comment]
During Beatrice’s and her teacher’s fight in chapter 3. Some of the effects for Beatrice’s attacks are not at the right resolution for 1080p.

**Comment by DogLover314** [comment]
In chapter 3, EVA-Beatrice's profile is mislabeled in the 1080p patch.
![20181228170131_1](https://user-images.githubusercontent.com/38626341/50529670-a931ed00-0ac4-11e9-963f-e346040c94cf.jpg)

Here is the direct text from the 1080p patch.
![ev2_1](https://user-images.githubusercontent.com/38626341/50529696-d1b9e700-0ac4-11e9-82a3-1ed99ad23133.png)

And the direct text from the 960p patch.
![ev2_1](https://user-images.githubusercontent.com/38626341/50530075-7ab61100-0ac8-11e9-9116-caf80fef2bfb.png)

**Comment by DogLover314** [comment]
Whenever the Chiester Sisters light bow trail image appears and text appears while it is on screen results in previous text being layered under it.
![20181230185828_1](https://user-images.githubusercontent.com/38626341/50552639-78d58480-0c65-11e9-9902-00bdcf08bb4b.jpg)

**Comment by drojf** [comment]
I think everything here is fixed now
