### ISSUE TITLE
Normal Patch - Ending Scrolls are slower

### ISSUE THREAD

**Issue by collinvman87** [07th-mod/umineko-question#118]
I downloaded this patch July of 2018 and played through all the games fine with no issues. I recently downloaded an update and tried it out today, on the same computer. I installed the non 1080p version. The ending scrolls are much slower now. In Ep 2 this isn't a problem since the music loops but in Ep 1 the music ends way before the ending scroll is finished.

**Comment by drojf** [comment]
Hi, i'm currently in the process of fixing all the credits timing for the 1080p version. I think the 1080p version is stable enough that it can replace the 'normal version'. I guess I can also backport it too, it's not too hard.

The old credits was framelocked (well, it tried not to be, but still was), so if you had a slow computer (integrated graphics), it would scroll extremely slowly, causing the music to end before the credits did. I've now fixed it up so it's timed.

Also note in some places that the music starts while the player is still clicking through text. This can make the time at which you reach the credits variable, which can mess with the timing if you are too slow or too fast. This isn't the case for ep1 credits, though, as the credits music starts exactly when the credits starts.

**Comment by collinvman87** [comment]
In the first ending credits scroll, on the line "This incident was later called by many names, such as 'The Rokkenjima Mass Murders'" "The" is spelled as "I'he"

**Comment by drojf** [comment]
I think all the credits needs a proofread. I have listed some other typos here: https://github.com/07th-mod/umineko-question/issues/113

Can you copy your comment into the other issue, then close this issue?

**Comment by drojf** [comment]
I'm closing this issue now, but feel free to comment in the other issue which is the same thing.

This issue: https://github.com/07th-mod/umineko-question/issues/113
