### ISSUE TITLE
1080p - Ep 2 Scene change effect offset

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-question#122]
This is the first scene change of episode 2:

![20190125013516_1](https://user-images.githubusercontent.com/1249449/51718031-72d19880-2097-11e9-8595-5d9eaee90b93.jpg)

**Comment by DoKu39** [comment]
![20190125135224_1](https://user-images.githubusercontent.com/37155215/51747086-b254b080-20a8-11e9-8815-28c214d39ab2.jpg)

The next one is offset too, i also did a screen of the text just after the change of scene.

![20190125135301_1](https://user-images.githubusercontent.com/37155215/51747126-d912e700-20a8-11e9-978b-61bb57f8fe41.jpg)

**Comment by drojf** [comment]
The latest commit should have fixed this kind of issues. Once you have finished the episode, you can re-download the script file from here: https://raw.githubusercontent.com/07th-mod/umineko-question/1080p/InDevelopment/ManualUpdates/0.utf (right click and download. Delete your old 0.u file and replace with this file, renamed to 0.u). Or you can restart the episode if you're still near the start of it.

If you installed the game after Jan 17, 2019, then you're safe - you can just replace the script as is and your saves should work correctly (test an old save works correctly just to be safe, though).

Let me know if you notice any more of the same issue in this thread, after you have applied the new script.
