### ISSUE TITLE
1080p patch mislabeld Gaap profile

### ISSUE THREAD

**Issue by DogLover314** [07th-mod/umineko-question#125]
Gaap's profile for chapter 4 is labeled with the name ANGE
![gap_1](https://user-images.githubusercontent.com/38626341/52741226-de29ce80-2fa2-11e9-8e16-7970dbeffb6e.png)

**Comment by drojf** [comment]
thanks for that, we'll get it fixed

**Comment by drojf** [comment]
This should be fixed now, and would be grouped under https://github.com/07th-mod/umineko-question/issues/130 anyway
