### ISSUE TITLE
rclick menu character descriptions needs re-check

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-question#130]
The character descriptions in `en\bmp\r_click\text\cha` are in need of a re-check against the original game's text - some descriptions have typos or refer to the wrong character.

edit: I made a script to create comparison images and have started going through them.

**Comment by drojf** [comment]
I've gone through the `cha` folder and marked the images which need to be fixed. I have NOT yet gone through the `tips` folder. You can download it here: [errorList_cha_only.zip](https://github.com/07th-mod/umineko-question/files/3077174/errorList_cha_only.zip)

Please note that some of the images which have already been fixed are in there (the ones already in the [question arcs rolling update zip](https://07th-mod.com/Beato/1080p/Umineko-Update-1080p-Rolling-ALL-OS.7z))

Here is a link to the comparison images I used to check them ( I generated them using the old/mangagamer and the new 1080p images), including the `tips` folder: https://1drv.ms/u/s!Ar-lAVeetlqhwUQyKHu8tmn_qn5s

If anyone wants to double check the `tips` folder just let me know, otherwise i'll get around it eventually

**Comment by tlm-2501** [comment]
Regarding the TIPS:

- Episode 2 seems to have missing full stops on page 2 of the game record. Episode 3 also has this issue.
- Episode 4 has an `O` instead of a `0` in the "Regarding Voyagers" tip.

Everything else appears to be okay.

**Comment by drojf** [comment]
I've fixed up the `cha` folder, and updated the 'rolling update' file which is distributed when you install the game: https://07th-mod.com/Beato/1080p/Umineko-Update-1080p-Rolling-ALL-OS.7z

I still haven't fixed the tips folder - might never end up doing it as it's fairly minor. I'll leave this issue open though, as it's still not fixed.

**Comment by drojf** [comment]
I think this is resolved now.
