### ISSUE TITLE
ADV Fonts missing

### ISSUE THREAD

**Issue by renaryugu** [07th-mod/umineko-question#138]
I can't enable ADV mode. When I try, the game pops up "ADV Fonts missing! Disabling ADV mode" at the top of the screen and then continues as usual. I manually installed the full patch about a month ago. Just curious if there's a file I can download (or if there's one that I already have and is just misplaced).

**Comment by drojf** [comment]
Hi there,

Make sure you've got the ADV pack installed: https://07th-mod.com/Bern/Umineko-ADV_Mode.7z

It is under the "Updates" section in the "Question Arcs" table but is easy to miss...might be worth looking through the list again, especially the updates .zip files: http://07th-mod.com/wiki/Umineko/Umineko-Part-1---Voice-and-Graphics-Patch/

**Comment by renaryugu** [comment]
That did it, I must've missed something in the updates list. Thanks!
