### ISSUE TITLE
Text issus

### ISSUE THREAD

**Issue by Maelstrom1** [07th-mod/umineko-question#14]
As requested, the bug report as a separate issue:
In addition, Idk if it was part of the new translation, but a portion of dialogue is missing from when, on night 1, Shannon walks back to the guesthouse with the cousins and a sleeping maria. It skips right from them walking to Batler saying how he wishes he was holding maria. (b/c shannon as a little too close to george). Oh, and, again, idk if it's purposeful or not, but some of Battler's lines are just straight-up missing spaces. Idk if either of these are Steam version changes, or unintended consequences.

I don't have the specific places, but, if I come across Battler being weird again, I will screencap and post it here.

**Comment by marakeusz** [comment]
I think I know what it is. I have version with fixes prepared. I will pull submit pull request soon..

**Comment by marakeusz** [comment]
Fixed (hopefully) in https://github.com/07th-mod/umineko-question/commit/92b5d8e5f6453192478df5d31a7cdc26141a8999

**Comment by DoctorDiablo** [comment]
@marakeusz fixed the issue with the missing lines, and I just fixed the 3 lines where Battler's dialog was missing spaces.  I did a regex match to make sure there were no other lines line that.  So I'm gonna mark this one closed.
