### ISSUE TITLE
Using "old sprites" mode skips part of game

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-question#141]
In 5c63974c2808958eb0e0fb52a5bef7aeb4562d53 (in Nov 2016), the following code was committed

```diff
 langjp「行くぜベアト。@/
 langen:dwave 0, but_3e331:^"Here I go, Beato.^@/
 
 textoff
 se1 20
 wait 200
 se2 20
 wait 200
 se3 20
 wait 1000
 se1v 2,100
 bg white,1
 bg G1F_S1cP,0
 ;ld r,$BEA_WaraiA1,0
-ld l,$BUT_odorokiB1,2
+notif %is_old_sprites = 0 ld l,$BUT_odorokiB1,2
+if %is_old_sprites = 1 jumpf
+	lsp 882,c_e0103_wall,0,0
+	lsp 881,c_e0103_a,0,0
+	print 2
 
 bgm1 53
```
(see https://github.com/07th-mod/umineko-question/commit/5c63974c2808958eb0e0fb52a5bef7aeb4562d53#diff-2294917ab8caed809b97634c8158249eL138017)

This code is missing a ~ after the jumpf, so it will skip to the next ~ that happens to be in the script.

I will hotfix just this problem right now, but if anyone feels like it, checking there are not any excessively long `jumpf` would be a good sanity check on all our scripts (like, more than 50-100 lines)

Since we are phasing out the "old sprites via toggle" option (we will support it via asset replacement), in the future this won't be a problem.

**Comment by tlm-2501** [comment]
Closing this since we've removed the sprite switching in-game entirely, leaving only the install-time switch.
