### ISSUE TITLE
Game path won't load in or work for Umineko

### ISSUE THREAD

**Issue by V-oss1** [07th-mod/umineko-question#180]
After installing the 07th-Mod Installer, I went to Umineko (chapters 1-4) since that's what I want to play. There was no game path automatically selected, so I typed in the alternative (shown below) game paths. Nothing happened (no game path found) so I went on the "Open File Dialog" box. The only thing I could select is "C:\Users\Name\Downloads\07th-Mod.Installer.Windows.exe", which keeps saying "C:\Users\Demetrius\Downloads\07th-Mod.Installer.Windows.exe" 

- My operating system is Windows
- I installed the game half a hour ago
- I am running the Full Patch
- I installed the game using the Automatic Installer

![Screenshot 2024-11-20 075741](https://github.com/user-attachments/assets/c546fca5-fda8-41c7-a332-5b898dc2eda6)

**Comment by drojf** [comment]
Hi, can you tell me where you installed the unmodded game (from steam, GOG etc.)?

For example, in this screenshot I have installed the game at `D:\games\steam\steamapps\common\Umineko`

The installer wants you to select the `Umineko1to4.exe` file located in that folder.

![image](https://github.com/user-attachments/assets/284531a0-cfc9-44eb-a85a-8df5c4fa27a5)

Please note the mod does not work with the really old original umineko releases (which run at 640x480 resolution, and have a different executable name than `Umineko1to4.exe`)

**Comment by andOlga** [comment]
We've resolved this person's issue via Discord a while back. They didn't own the game and assumed we provided the whole thing, not just the updated content.
