### ISSUE TITLE
Various Volume Issues

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-question#20]
As per https://github.com/07th-mod/umineko-question/issues/13 and https://github.com/07th-mod/umineko-question/issues/1#issuecomment-249711844 we should change the volume higher, even if it results in clipping sometimes. I played through some of the game with `default_vol 70` (the default value) and `voicevol 60` and it seemed alright. Any play testers want to comment on what settings they used? 

@marakeusz used `default_vol 70`, `voicevol 75` https://github.com/07th-mod/umineko-question/issues/11#issuecomment-249424065 

Perhaps we should just instruct users how to change the volume in the install instructions :)

**Comment by BBattler** [comment]
BGM volume is too low while background volume is too high (rain especially).

**Comment by Maelstrom1** [comment]
This is true, and often times the music changes volume suddenly, for no reason. I fixed the sfx by just editing and replacing the .wav files with audacity, lowering the volume by a considerable amount.

**Comment by marakeusz** [comment]
This issue was raised because we are completely aware of that problem. SFX is easy to fix by just setting default_vol to original 70.

**Comment by drojf** [comment]
I added a new script file to the last release (v1.1) with default_vol 70, voicevol 60. If the voice volume is too low or there are still issues I'll go default_vol 70, voicevol 75 as marakeusz has set it. If there are no problems with my edited script file then I'll make that the default one.

Please download and rename to 0.utf: https://github.com/07th-mod/umineko-question/releases/download/v1.1/0_dvol70_vvol60.utf

Also, incase we decide to do something different next time @Maelstrom1 , which sfx files did you fix? Did it work in all instances or just most of the time? In theory I could make a script to fix the `chvol` commands so that they all scale on default_vol, but since it was reported that setting `defaultvol` back to its default value was good enough I haven't looked into it.

**Comment by Darts502** [comment]
I tried the patch you released, for me it sounds really quiet (the bgm that is) and I have no idea how to edit the values myself (I have no idea about scripting or anything). If anyone could give me a quick run down on how to edit the values myself, that'd be awesome.

I checked the 0.utf file in notepad, and I couldn't find any text with "vol" that refers to game volumes.

**Comment by marakeusz** [comment]
> I checked the 0.utf file in notepad, and I couldn't find any text with "vol" that refers to game volumes.

That is strange because there is a lot of "text with vol" in the script.

More importantly -  are you absolutely sure you dowloaded **0_dvol70_vvol60.utf** file and renamed it to **0.utf**?

**Comment by drojf** [comment]
To be honest I didn't test the script file myself, so there's a chance I messed it up - however I only changed two lines of the script.

The lines of code you should change are the following. I wouldn't use notepad since it's not suited for large text files (well...notepad++ isn't either, but it works somewhat).

You want to change the following lines (for the version of 0.utf I linked in this thread, it's on line 183-184):
```
numalias default_vol, 70
voicevol 60
```

Do a ctrl-f for `default_vol` and it should turn up near the start of the script.

The `default_vol` controls the volume of the music, SFX etc, shown above as 70/100%
The `voicevol` controls the voice volume.  shown above as 60/100%

If you change the values (eg change `voicevol` to `0`, effectively disabling the voices) and it has no effect, something's gone horribly wrong :S.

**Comment by drojf** [comment]
This should be fixed as we added the new volume system from the Answer arcs - see:

- https://github.com/07th-mod/umineko-question/commit/e058e0746a7cad6c126b07621fddcea6ceee9059
- https://github.com/07th-mod/umineko-question/commit/03fae6191f820a70353e1da745e1393869674e31
- https://github.com/07th-mod/umineko-question/commit/13b2df62fb1d9c5177c598b019e4e734c4e21097
