### ISSUE TITLE
Sprite offset Issues

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-question#33]
In https://github.com/07th-mod/umineko-question/issues/30#issuecomment-252452365 it was reported that sprites were offset in the meta world. After looking into this issue it appears that this was due to the built in function [`amsp`which is "Absolute Move SPrite"](http://unclemion.com/onscripter/api/NScrAPIm.xml#amsp) . Since the function takes in absolute values, I'd assume that all calls to `amsp` were 'broken' when I implemented the widescreen patch. 

Instances of `amsp` where the arguments are numbers can probably be fixed by scaling the numbers to widescreen equivalents. Unfortunately there are a lot of instances of `amsp` which don't take a number as argument but a variable (since they are used inside a function call). Probably the best way to go is to define a custom amsp which scales the width values to widescreen (yes, in onscripter you can redefine engine defined functions). This will automatically override all calls to amsp. Any Onscripter experts here? I'm imagining something like:

```
*amsp
    ;get arguments to amsp somehow here
    mul %old_width, 16
    div %temp, 9       ;div truncates remainder - maybe do some math to make it round properly
    _amsp %orig_sprite, %temp, %orig_height
return
```

Thinking about it, I probably should have done it this way instead of modifying the values in the 'setwindow' function...

Any other issues related to sprites being offset should be put in this issue.

**Comment by drojf** [comment]
Ok, I think I have something working...I've been busy lately so haven't worked on this much. I haven't tested it that well, but I thought I might as well put it out here so people can try it or to stop people repeating what I've already done.

Here's what I found so far 

- Since amsp can take 3 or 4 arguments, replacing the `amsp` function won't work properly unless you change each call to amsp to use 4 arguments. To fix amsp taking 3/4 arguments, I simply made every call to amsp in the script have 4 arguments if it only had 3, replacing the last argument with '255' (full opacity).

- Scaling is a bit more involved than I thought. When you call amsp to move the sprite, it moves it according to its bottom (top?) left corner. Therefore, in the script, they have done some maths so that all coordinates fed to amsp are have half the sprite's width subtracted from it (see the `*mldt` function for an example), such that if you say 'move to position X', the sprite will be centered around 'X', not have it's corner at 'X'. 
 
- To correctly scale the x coordinate the sprites are moved to, you must scale from the center of the screen. This involves a series of transformations as shown below:




```
defsub amsp

....

numalias uq_amsp_0,%0 : inc %0 ;07th mod amsp temp vars
numalias uq_amsp_1,%0 : inc %0 ;作業用変数
numalias uq_amsp_2,%0 : inc %0 ;作業用変数
numalias uq_amsp_spr_w_3,%0 : inc %0 ;作業用変数

....

*amsp
    getparam %uq_amsp_0,%x,%uq_amsp_1,%uq_amsp_2
    
    ;get the size of the sprite which amsp was called with
    getspsize %uq_amsp_0,%uq_amsp_spr_w_3,%witchh7,%witchh8
    
	;sprite 'width' is the total width divided by 4, probably due to the special 'mask' 
    ;spritesheets the original game used - 画像の幅/4　で画像中心からの幅が求められるので
    ;（立ち位置のX座標からその幅を引く）
	div %uq_amsp_spr_w_3,4 

    ;add sprite width/4 to get the original desired center-of-sprite position
    add %x,%uq_amsp_spr_w_3

    ;center around zero (still in 640x480 space)
    sub %x,320

    ;scale from center (after transform, now in 853x480 space 16:9)
    mul %x,16
    div %x,9

    ;uncenter around zero, but move zero to center of 16:9 screen  (853x480 space)
    add %x,427

    ;finally, add the sprite width back (853x480 space)
    sub %x,%uq_amsp_spr_w_3

    _amsp %uq_amsp_0,%x,%uq_amsp_1,%uq_amsp_2
return
```

Here is the [TESTING script 0.zip](https://github.com/07th-mod/umineko-question/files/546405/0.zip) - it automatically SKIPS to the first time you enter the meta world (when you start a new game), so spoilers if you haven't played that far in (!!). Later I'll release this properly. This might also fix some instances of sprites being in the wrong position, except for when the clock interlude is shown (this calls the `amsp2` function)

**Comment by ReitoKanzaki** [comment]
I was able to fix this in a recent commit. It was quite simple.

```
*mldt

	getparam %meta_tmp1,$witchh2,%meta_tmp3,%witchh15  ;立ち絵位置（l左　C中央　ｒ右）、立ち絵、表示方法, trans

	gosub *ld_inner

	if %meta_tmp1 = l mov $last_meta_l, $witchh2 : mov %last_meta_l_trans, %witchh15 : mov %meta_l_on,1
	if %meta_tmp1 = c mov $last_meta_c, $witchh2 : mov %last_meta_c_trans, %witchh15 : mov %meta_c_on,1
	if %meta_tmp1 = r mov $last_meta_r, $witchh2 : mov %last_meta_r_trans, %witchh15 : mov %meta_r_on,1

; end 2x

	mov $witchh15,$witchh12
	if %hide_new_sprites = 1 && %is_old_sprites = 0 && %hide_bgsp2_cg = 0 mov $witchh15,":r;bmp\placeholder.png"

	;左の画像が前に来るようにする。レイヤー293左　294真ん中　295が右
	if %meta_tmp1 = l mov %meta_tmp4,msp_l lsp msp_l,$witchh15,0,0
	if %meta_tmp1 = c mov %meta_tmp4,msp_c lsp msp_c,$witchh15,0,0
	if %meta_tmp1 = r mov %meta_tmp4,msp_r lsp msp_r,$witchh15,0,0

	;スプライトの画像情報を取得（%meta_tmp5に画像の幅が代入される）
	getspsize %meta_tmp4,%meta_tmp5,%meta_tmp6,%meta_tmp7
	;画像の幅/4　で画像中心からの幅が求められるので（立ち位置のX座標からその幅を引く）
	div %meta_tmp5,4
	;if %meta_tmp1 = l mov %x,160
	if %meta_tmp1 = l mov %x,213  ;convert to widescreen
	;if %meta_tmp1 = c mov %x,320
	if %meta_tmp1 = c mov %x,427  ;convert to widescreen
	;if %meta_tmp1 = r mov %x,480
	if %meta_tmp1 = r mov %x,641  ;convert to widescreen

	sub %x,%meta_tmp5
	amsp %meta_tmp4,%x,0,%witchh15
	print %meta_tmp3
return
```

All I did was change the center positions to quarters of 854.

**Comment by drojf** [comment]
That won't fix all instances of amsp, hence my solution which fixes all instances where sprites are moved to a particular place on screen. I did test my solution a little and it worked fine, did you have problems with my version?

**Comment by ReitoKanzaki** [comment]
Yeah. It would still need some work. The cursor positions are offset from the end of the text. Buttons are all over the place. And the sprites are pushed too far over. 

It seems amsp is mainly called to display menu assets and BGM Mode assets. There is one scene where it is used to display sprites for Jessica vs. Ronove. That will most likely get replaced anyways as I believe the PS3 version uses a different scene and actually has CGs. Once I was finished with the game CGs, I had planned on working on the menu and re-positioning all of those by hand.

I'll go ahead and change my implementation of *mldt to use _amsp for now.

**Comment by drojf** [comment]
ah i didn't notice the cursor offset thing. I couldn't find anything wrong with the buttons though. In any case, it may be better to rename my function something like "amsp_scale_to_widescreen", and then replace "amsp" wherever it is needed, in case we need to use it again in multiple places in the script.

If this really is the only this instance of sprite offset that needs to be fixed, your solution is fine, and we should just go with that. I did what you did before, but was worried the other amsp instances would have problems.

There is also one instance of amsp2 which is used to render the clock during the intermission, you might want to have a look at that as well, as it should be easy to fix (and the clock does come up quite often).

**Comment by ReitoKanzaki** [comment]
amsp2 is also used in Episode 3 after Kanon fights Lucifer.

To be honest, unless we plan to give people an option to change between aspect ratios like how they can change through sprites, I don't see a reason to alter the behavior of a built in function. If we are going to make an option, then we would need to redefine all lsp* functions as well.

**Comment by drojf** [comment]
yea I agree, should scrap what I was doing originally, I just meant that you could make a function called "amsp_scale_to_widescreen" and reuse it in the script if necessary. But of course, if it's only going to be used once then there's no point making a function and you can just change the one instance of it as you have showed me in this comment thread.

**Comment by drojf** [comment]
Hey @ReitoKanzaki did your change make it into the recent release? if so I'll close this issue.

**Comment by drojf** [comment]
it has been nearly 2 years so I think this should be closed :S
