### ISSUE TITLE
New Patch does not allow me to save or load states:

### ISSUE THREAD

**Issue by Yugikun** [07th-mod/umineko-question#48]
Hey. I'm playing the Steam version (pretty sure this is the MangaGamer release, but I'm calling it by steam just in case I'm wrong) of the game, and have recently downloaded the latest patch (after downloading it before in the version before CGs). However, when trying to access the game afterwards it forbids me from either saving or loading, as the clickbox required to use it isn't there. Picture of issue here: https://gyazo.com/321eb91b08c250840e6d72b8198d178c . Switching back to how it was before the patch fixes the problem and allows me to play the game, but I would like to use the current patch, so if there's a way I could fix this that would be great.

**Comment by DoctorDiablo** [comment]
Hmm... it's working ok for me: http://imgur.com/gallery/YafEG  Looks like it's just not rendering the button graphic.  Can you double-check that you have this file on your system: Umineko\bmp\system\loadarea_w.png

Also, would you mind zipping up your saves folder and uploading it?  Maybe I'll be able to recreate this problem using your config.

**Comment by Yugikun** [comment]
Problem fixed! Although searching for it did nothing, clicking on the files within there allowed me to find "loadarea" without the "_w" at the end. Changing the file name to what you had it as allowed me to select it again, so now I'm able to save/load. Thanks!

(Should I still zip up my saves folder, though?)

**Comment by DoctorDiablo** [comment]
Glad you got it working.  Don't worry about uploading your saves.

I verified that the package contains the image you were missing, so I guess this was just something funky happening during the install.  Gonna mark this as closed.
