### ISSUE TITLE
Possible to replace icon in custom .exe?

### ISSUE THREAD

**Issue by jwgrlrrajn** [07th-mod/umineko-question#50]
So, looking at the custom .exe file required by the mod, I notice it's still using the Beatrice face from the Steam sprites. I went ahead and made a custom .ico file that tries to match the style of the existing icon, but has PS3 Beatrice's face instead. Would you be interested in using it?

https://drive.google.com/file/d/0ByXn28otvziTaVZ6R3dTQ1o5NWc/view?usp=sharing

**Comment by drojf** [comment]
Hmm, i guess it might be an easy way to differentiate the patched version vs the normal version. How do you actually apply the .ico to the .exe (permanently) though? I never tried to do that before...

**Comment by jwgrlrrajn** [comment]
Not sure. I've been making do with the icon replacing the shortcut's default icon.

**Comment by jwgrlrrajn** [comment]
Ah, found it. I used a tool called "Resource Hacker." Here's the modded .exe if you want to use it. https://drive.google.com/open?id=0ByXn28otvziTZkZIemlUVzlqVFU

**Comment by ItaloKnox** [comment]
That's a great enhancement, I'll keep it in mind when we release the next set of fixes. Thanks for making it!

**Comment by jwgrlrrajn** [comment]
Since I'm part of the modding team now, do you want me to go ahead and replace the icon in the v2.5 patched .exe file?

**Comment by ItaloKnox** [comment]
Go ahead, I think I forgot this one after I released the last update.

**Comment by jwgrlrrajn** [comment]
Alright, it's done now. Issue closed.
