### ISSUE TITLE
Known Issue but can't find a solution: Can't Save/Load (Windows, Steam Version)

### ISSUE THREAD

**Issue by Stallowned** [07th-mod/umineko-question#51]
Greetings!

This issue seems to be known, but the Threads I found concerning this topic are people with a pirated copy of the Game. I bought Umineko yesterday via Steam and was interested in the Patch because the Game is far more atmospheric with voices and of course a better resolution.

I'm pretty inexperienced when it comes to modding, you can say, I'm less than an amateur. So I was pretty surprised how easy it was to patch the Game. And everything worked fine. The Voices and the Graphics. A day later, my mood went down. I started a new Game, played 30 minutes (lucky me it was only such a short time) only to find out I couldn't save the Game. And it was clearly not the save/load menu when I first started the Game without the Patch.

So what have I done wrong?

Here is a list what I "Have" done before I installed the Patch:

- Downloaded the Game via Steam
- Tested the Game. Created a Save at the beginning of the Game
- Downloaded the Patch, installed voices and graphics.

How have I installed the Patch?

Now, this is a little tricky. For a Newcomer, the page where the Patches are listed are some kind of messy.

I visited the Release-Page. I downloaded voices and graphics and everything related to the instruction of Patch-Version 2.0:

> Extract umineko-voices-*.zip inside your Umineko folder.
Rename the file 0.utf inside your Umineko folder to 0.utf.bak (or just backup it to a folder called backup)
Place the patched 0.utf file inside the folder
Extract umineko-graphics-*.zip inside your Umineko folder.
Rename the file Umineko1to4.exe to Umineko1to4_old.exe
Put the new Umineko1to4.exe inside the folder
> 

So, is there any mistake I made? Should I have start with Patch 1.0 and then installing 1.1 and then 2.0? Or was it Okay to just follow the steps of the installation of Patch 2.0?

I'm using Windows 7 (64) by the way. Steam haven't updated the Version I played, this seems to be the most current version.

If this Thread already exist, please link me to the solved issue. I appreciate any help.

Best Wishes

**Comment by drojf** [comment]
> Should I have start with Patch 1.0 and then installing 1.1 and then 2.0? Or was it Okay to just follow the steps of the installation of Patch 2.0?

You just need the files listed in the 2.0 Release: https://github.com/07th-mod/umineko-question/releases/tag/v2.0 , you do not need any other version of the files as prerequisites.

> Can't Save/Load (Windows, Steam Version) 

Someone actually reported an error exactly the same as this earlier, please see https://github.com/07th-mod/umineko-question/issues/48 , however we closed it because we thought it wouldn't happen again. Could you confirm if it fixes the problem/if you have the same problem? 

Specifically, check whether "Umineko\bmp\system\loadarea_w.png" exists. The problem-asker fixed it by renaming loadarea.png to loardarea_w.png, but ideally we want to know how this happened in the first place.

**Comment by Stallowned** [comment]
@drojf

Thanks for the quick reply! If I just need to download the 2.0 Release, this is a big help because that mean I haven't done anything wrong when it comes to the installation to the Patch.

And yes, I can confirm it, it is the same problem the user had you linked here. Oh, yes, and even my complete menu changed after I installed the Patch. Normally, you see the mansion in the main menu. The background is missing in my version. I thought this was fine after installing the Patch, but I guess I was wrong. The problem-asker attached a picture to his Post and it looked completely normal, just like the version before I installed the Patch.

So, I re-installed the Game now, removed everything related to the Patch and re-downloaded the Game. I will do everything from the start now and if it happen again, I will check the folder with the "loadarea". Wish me luck!

**Comment by Stallowned** [comment]
Ok I'm back (just using a new post because I'm writing about the solution):

It was just like the user from the other Thread explained. I re-downloaded the Game, installed the Patch including voices and graphics, but nothing happened. Couldn't load or save. There is always this one save game I can't delete from my test-run. Guess this is due to Steam-Cloud.

I went to the folder you told me to go and searched for "loadarea.png". Found the file, corrected it to "loadarea_w.png". Started the Game, tried to load the old save file (which won't work with the patched version) and bingo, it worked. It crashed the Game because it was an old file, but it worked. I was able to load the save and the red backgrounds were back.

I started a new Game and tried to save. But this still haven't worked. So I renamed the file "savearea.png" to "savearea_w.png". And finally, I can save.

I have voices, graphics, I can save and I can load, but there is still the background from the main menu missing. This is minor and doesen't bother me the slightest, but I fear there might be other problems left with the empty graphics. I sure hope the missing background in the main menu is the only problem left.

The moment I started the Game after the re-download (tested it without the Patch), the background in the main menu was there. After the Patch, it was gone like the backgrounds of the save and load buttons. I will attach a picture of my main menue at the end of my post.

Again, many thanks for helping me and find a solution in such a short time.
![black](https://cloud.githubusercontent.com/assets/24869866/21584966/5ea7acf6-d0b6-11e6-85f5-2881ff3e9eaf.png)

**Comment by Stallowned** [comment]
Yes, unfortunately, when you uninstall with Steam a Game, you have to manually delete the folder to get a true uninstall. Also, I used the 0.utf from the Patch (an renaming the old one), but like you alreary tested yourself, it works perfectly fine for you.

I'm using good old WinRar ;D
But normally, even WinRar will tell you if a file is broken. But it's still a good idea to try 7zip.

My guess is, it is most likely a problem with my Laptop/System. Even when the background in the menu is working without the patch, it took the system about 0,5 seconds to load the background (this only occurs in the main menu, in the Game itselfs, everything works as it should). In other words, it pops up, it's not there from the beginning. And with the Patch, it's gone completely.

Maybe I give the graphics a re-download.

>Could you run the following windows command in the root Umineko directory (it extracts the file tree structure)?> 

At this point, it seems my knowledge reached it's limits, because I can't follow you anymore xD
This is a combination of commands I never heard of and English isn't my native language ; /

I will give you an Update if I find a solution when I try re-downloading the graphics and using 7zip.

**Comment by Stallowned** [comment]
Wonderful!

Seems like my problem is fixed. Again I deleted everything related to the Game and re-installed it. I downloaded 7zip, I forgot how superior the program is over WinZip. Then, I clicked again on "Graphics" on your Download-Page. But this time, I wasn't redirected to "Mega" but it loaded directly from the page. It was a Package over 3 Gigabyte, the one I loaded from "Mega" was just aboe 2 Gigabyte.

I extracted the "Umineko Graphics Master" Package in my Umineko folder. Again, no Menu Background, no save and no load menues. Simple logic, I went back to the Umineko folder and copied everything from the extracted  "Umineko Graphics Master" folder to the main folder of my Game. And this fixed everything.

It seems I downloaded an older version of the graphics. Don't know why I haven't found this big file in the first place. The next mistake I made was, I never copied the data from the "Umineko Graphics Master" folder to my main folder (the same reason I had no voices at my very first try).

So, all in all I praised myself to early for installing the Patch with no errors. I'm just glad it worked and without your help, none of these problems I had were solved. I will give Umineko a try later this evening and see how stable this is.

Best Wishes!
![umineko](https://cloud.githubusercontent.com/assets/24869866/21596610/977b6ae0-d13d-11e6-8762-7d2730f581c4.png)

**Comment by drojf** [comment]
I realized that if you followed the instructions we provided to the letter, it wouldn't work, due to the funny "umineko-graphics-master-5527f..." sub-folder. I've included instructions to move the folders out of that folder to prevent that happening, not sure if it's some git issue where it will always wrap the folder in its own folder :S. I also specified what folders should be created so users can check they did it right.

Also, I changed the link on the main page to go directly to the latest release (it doesn't show older releases anymore), so it should be harder to get the wrong version of the game now.

thanks for your report, I'll mark this issue closed for now. If you find more problems on your playthrough please open a new issue.
