### ISSUE TITLE
Game crash after loading (Mac steam version)

### ISSUE THREAD

**Issue by jono9009** [07th-mod/umineko-question#57]
So I tried installing voices only. My Umineko folder looks as such: 
![screen shot 2017-03-18 at 11 42 57 pm](https://cloud.githubusercontent.com/assets/26514817/24077959/ad6c15fc-0c34-11e7-88a7-f384ce6a9baf.png)
I changed the utf by opening it in textedit and replacing everything with the provided 0.utf. 
When i tried loading my save I received this:
![screen shot 2017-03-18 at 11 46 56 pm](https://cloud.githubusercontent.com/assets/26514817/24077983/37bdad42-0c35-11e7-8595-609b18586a28.png)
No textbox or anything. My game crashed shortly after. 
Is something wrong with the script? Thank you in advance.

**Comment by drojf** [comment]
I think if you want just the voices (no widescreen, no background, no new sprites), you should use this old script: https://github.com/07th-mod/umineko-question/commit/ff5cd239c514fb33ca610c79ef76ab3fcf1d6beb

you don't need to patch anything else at all, just replace the entire 0.utf with the one above

I did a writeup here: https://github.com/07th-mod/umineko-question/issues/11

**Comment by drojf** [comment]
I think if you want just the voices (no widescreen, no background, no new sprites), you should use this old script: https://github.com/07th-mod/umineko-question/commit/ff5cd239c514fb33ca610c79ef76ab3fcf1d6beb (click 'view', then click 'download)

you don't need to patch anything else at all, just replace the entire 0.utf with the one above

I did a writeup here: https://github.com/07th-mod/umineko-question/issues/11


Unfortunately, there are some bugs in the voices which hadn't been fixed in that version. I don't know how many fixes there were.

Opening in text editor and copy pasting isn't the best way to do it - it's probably better to just replace the file entirely.

**Comment by jono9009** [comment]
I am fairly certain I used the old script. It's only 15 mb correct? it downloads as a text file so directly replacing it causes the game to not start at all.

**Comment by drojf** [comment]
just rename it to 0.utf if it is a text file and it should work fine

**Comment by drojf** [comment]
also, if you're using the old script, you should run the non-patched exe - the patched exe is only for widescreen mode and the old script had no widescreen mode

Another alternative is to use the new script and not download the updated sprites. It should just revert to the old sprites I think. There will be black bars on the background if you don't download the new backgrounds, though.

**Comment by jono9009** [comment]
I tried added the txt file and renamed it to 0.utf, I received this when i tried opening the game:
![screen shot 2017-03-19 at 12 04 22 am](https://cloud.githubusercontent.com/assets/26514817/24078044/cfc4e1a8-0c37-11e7-98a4-a77927211ee5.png)

**Comment by jono9009** [comment]
also I'll remove the the patched exe, thank you.

**Comment by drojf** [comment]
does macosx hide file extensions like windows does? you may need to enable "show known file types" if it does. then you can see the true file extension

**Comment by jono9009** [comment]
I turned on true file extensions but everything looks the same.
Here is an updated Umineko folder:
![screen shot 2017-03-19 at 12 10 54 am](https://cloud.githubusercontent.com/assets/26514817/24078062/9fa8a49a-0c38-11e7-976a-78170e99b58e.png)

**Comment by jono9009** [comment]
Ok so I just changed the text to a utf file, but upon starting up the game I get the same screen. 
![screen shot 2017-03-18 at 11 46 56 pm](https://cloud.githubusercontent.com/assets/26514817/24078087/32e070ee-0c39-11e7-9c6a-a71c365ab939.png)

**Comment by drojf** [comment]
Are you sure your Umineko1to4 is not patched? The screen is wider than normal, normally an unpatched game won't have the black borders. 

As in, you need the original Umineko1to4 which came with steam. You can force steam to revert everything by clicking "force recheck" in the steam game options, but remember to move the important files to a backup folder.

**Comment by jono9009** [comment]
I verified the integrity of my game files and still have that black border. I may not have been paying attention but I think I always had it.

**Comment by jono9009** [comment]
Should I try uninstalling and reinstalling after I backup my saves?

**Comment by drojf** [comment]
er...I think before all that, you should try downloading the latest 'normal' 0.utf and running it, and seeing if the game crashes or not. This one: https://github.com/07th-mod/umineko-question/releases/download/v2.0/0.utf

If it still runs, you may not need to use the old files at all. please try that first.

**Comment by jono9009** [comment]
I tried using the new utf, Unfortunately I can't even see the main menu:
![screen shot 2017-03-19 at 12 30 51 am](https://cloud.githubusercontent.com/assets/26514817/24078137/605f5448-0c3b-11e7-99ac-d14c4442b0fc.png)

**Comment by drojf** [comment]
Do you still have the patched .app file? Please try running that. I think you were right - you were running the unpatched version before, but it was fullscreen so of course it would have black borders on the side :S.

**Comment by drojf** [comment]
er sorry, I just tested it out on my computer. I don't think running the new 0.utf will work, only running the old 0.utf (unless you want to install the background sprites).

**Comment by drojf** [comment]
What is inside that "arc" folder? I don't seem to have one in my umineko directory...

**Comment by jono9009** [comment]
the arc folder has cgs for the steam version along with other things.

**Comment by jono9009** [comment]
![screen shot 2017-03-19 at 12 40 03 am](https://cloud.githubusercontent.com/assets/26514817/24078170/b837daa4-0c3c-11e7-97eb-edd56968810c.png)

**Comment by jono9009** [comment]
It was originally archived but I unpacked it. Will it cause trouble for the game?

**Comment by drojf** [comment]
er...maybe? I'm not sure, but move it elsewhere for now, so at least that is out of the question for causing problems.

Also, are you loading a previous save to test things? Usually that can have problems, you should start the game from the beginning to see if at least that works OK.

**Comment by jono9009** [comment]
HALLELUJAH! I started a new game and I have voices! My problem WAS that I was loading a previous save.
![screen shot 2017-03-19 at 12 49 34 am](https://cloud.githubusercontent.com/assets/26514817/24078210/f3c7eaae-0c3d-11e7-9089-f83cde6ffa59.png)
Thank you so much!

**Comment by drojf** [comment]
sorry, I should have read your first post more carefully :(. I'll marked this as closed, and make a note somewhere about save games...I don't think that's explicitly stated anywhere because we assume people will patch the game before they play it, which may not always be the case.

have fun :-)

**Comment by drojf** [comment]
ah jono9009, if you're still here, I just noticed that one of our members has been keeping the "voice only" version up to date with the changes we've made. it's located here: https://github.com/07th-mod/umineko-question/blob/master/InDevelopment/ManualUpdatesVoiceOnly/0.utf but I'm not sure if it's been tested

btw, where did you read we had a voice only patch? I only have that one comment in the 'issues' section...

**Comment by jono9009** [comment]
That's exactly where I saw it. Under open issues patch "options" there's a voice only option with instructions. I didn't want updated sprites and cg so I just followed that. Thanks for the heads up.
