### ISSUE TITLE
Small Visual Modifications and Darker PNGs Question

### ISSUE THREAD

**Issue by Forteissimo** [07th-mod/umineko-question#58]
So a few days ago, I modified a few things that were bugging me a bit and I'd like to hear what you guys think. I originally posted this in the CG and CG Sprite thread, since it’s only a couple visual updates, but given how I also meant to ask about a certain issue I noticed with PNG images, I thought I'd might as well make a new thread.

https://mega.nz/#F!gYREzBAC!mFvrZIzCdROfLd3pKRNe8g

So first off are the character sprites - in the original PS3 version, sprites weren’t entirely displayed as they are, but are actually slightly cut off at the bottom and appear 'bigger' - this was also imitated in Umitweak's Chiru patch. So I gave the sprites the same treatment, since I had mistakenly resized the sprites as fully they are in the first batch. I also took the chance to revisit and add expressions/poses that seemed more appropriate on certain characters. (Red-eyed Kanon, for instance, whose sprites were missing at first)

Some slight changes to the 0.utf file were made too, including fixing a few weather inconsistencies where the cloudy version of a background should've been used instead if the normal one – specifically, the scene with Maria’s rose after the beach and the first murder in episode one. There’s still a whole bunch of scenes I’m sure need the same treatment in all other episodes, though.

This script file also features a wider text space similar to Higurashi's and the alternate outfits for Jessica, Maria and Rosa. I'm pretty sure I got all of the scenes that use these sprites down, but even so, it'd be great if you could confirm they're working, just in case.  For Jessica drop the images in a folder named '2', same goes for Rosa's sprites, while on Maria's the folder should be named '3'.

I also removed the Pachinko CGs altogether from the script file. While I understand the intention to allow the reader to experience both CGs, I feel that having the clashing art styles may be a bit unaesthetic. 
On that note, I also reworked some of the split CGs with smoother cuts now. I imagine most CGs were resized using a bicubic resampling or something along those lines, and while the difference may very minimal, I'm not too fond of the heavy automatic sharpening added to pictures. Most of the character sprites were resized using a bilinear resampling, with a _very_ subtle sharpening over them in some cases, so I did the same for a few of the CGs where I felt necessary.

Among other updates are some things like Eva’s web, the Chiester’s light arrow, ware.png, repositioned maps, butterflies and barriers, rain overlays rescaled in waifu2x since the previous ones were a bit blurry, Goat-kun’s memories, the backgrounds for Kinzo’s door and the background for the main hall with the curtains closed, removing the spinning from Ange's CG (as I felt was also a bit unnecessary), Rosa's CG in episode 2's final scene and wider bio sprite dimensions for characters that needed more space (Kinzo, Goats, Eva Beatrice, etc.), since they were slightly cut off at the right. 

So putting all that aside, about that PNG problem I mentioned, I dunno if this issue's been addressed before or not, but there's this strange darkening and slight border added to pretty much all .png images. It's particularly noticeable in slightly transparent backgrounds, and it's bothering me quite a bit now that I'm just noticing it. 

For example, I've got [this logo](http://i.imgur.com/Z27Quu7.png) used at the title screen, so naturally, the final result should end up looking [something like this](http://i.imgur.com/3tNBLFc.png) in-game, right? But when actually seeing it in action, [the logo ends up getting darkened in the more opaque areas](http://i.imgur.com/63gvccf.png) (Beatrice's silhouette and the eagle crest).

I would like to know if this is caused by the engine used and not something that can be modified through the script. It's not really something too noteworthy or anything, but I thought it'd be worth asking since I figured you guys might have a much better idea on why this could be happening.

**Comment by Forteissimo** [comment]
Not that much of a substantial update or anything, but I revisited the character bio buttons since the previous ones were a little choppy and I wasn't liking what I had done for the Chiester/Stake buttons, so I made [these](http://i.imgur.com/DbB5yOj.png) instead. I think they look better and match the original buttons. 

Also updated the dimensions on some full body sprites that got cut off at the bottom (Kinzo, Rudolf, Stakes, etc.). You can find these in that 'r_click.7z' file I just uploaded to the Mega folder.

**Comment by Forteissimo** [comment]
@drojf @ItaloKnox Sorry for going as far as bothering you, especially with how busy you've been with the Higurashi releases, but did the notification for this thread get through in the first place? Just making sure.

**Comment by ItaloKnox** [comment]
Crap, I got the notification, read it and completely forgot to reply since I've been really busy with Higurashi. We're remaking the whole patch from ground up so that's taking a lot of time. I'm sorry for ignoring you.

I don't know what is wrong with Mega here but it seems to be loading and reloading the page everytime, so I can't see your update properly. Can I assume you need those uploaded in the graphics patch? If that's the case, is it all of them or some in specific? There's a lot of stuff to update so I don't think I can do it in my local machine, I will have to use my remote machine to do this. It will take some time but I think it should be uploaded in a few days, the machine is littered with Higurashi stuff that I can't delete right now, so that complicates things a little further.

About the issue with PNGs, I don't know exactly what causes them. Sorry about that, I think @drojf might be the right person to ask that.

Be sure to bump this thread by tuesday or wednesday, my server should be clean and the heaviest Higurashi stuff should be done by then. I'll take care of it, Umineko needs some love as well.

**Comment by Forteissimo** [comment]
Oh no, that's okay! It's perfectly understandable, these are only a couple touch-ups anyway, so it's not that big a deal. :>

Oddly enough, the same happened to me earlier when trying to open the folder. Must be a problem with Mega or something. Even so, I just made a whole new 'Umineko Updates.7z' file and uploaded it just in case, this one contains each and every update listed above. Unless I got the folder names wrong for some reason or other, which I really doubt, it's only a matter of extracting the  7z file into the Umineko folder and letting some files get overwritten.

https://mega.nz/#!lF413C6Q!2-U8KKaqaAGqA_p9E4ykVA1_hZlQQvGlYc4hfGWV3zI

This is unrelated, but I also made a custom [grid picture](http://i.imgur.com/kgI8WVK.png) resembling the one used in the Steam release, just in case anyone would wanna change theirs to match the PS3 patch.

**Comment by ItaloKnox** [comment]
That's great, this really helps me a lot. I'll see if I can do that today (it's 2AM here, so later). Shouldn't be a big issue other than freeing space and doing a few commands. I also really like the picture, guess I'll be using this one in Big Picture mode from now on.

Thanks a lot, I'll give you an update later!

**Comment by Forteissimo** [comment]
Whoops, almost forgot to upload the 0.utf too. Sorry about that.

https://mega.nz/#!oQJiwJIL!fAahFcbmKUr8ABHczBrZ9Ci1vSvkpk2pDq1Jxe4guP0

**Comment by ItaloKnox** [comment]
There you go, [release v2.5](https://github.com/07th-mod/umineko-question/releases/tag/v2.5). I don't think I missed anything, but I'll give it a proper playthrough later. Give me a heads up if there's any issues.

**Comment by Forteissimo** [comment]
Okay so while skimming around certain scenes, I came across this [awful image issue](http://i.imgur.com/i1RrCut.png) where certain areas turn transparent for some strange reason, turning the pictures into this [glitchy mess](http://i.imgur.com/IFCNSNA.png).

I have absolutely no idea what might be causing it, but I messed around with the images basing myself on the original versions and managed to 'fix' it by placing a single white pixel on the corner of each image. At first, I tried placing the pixel somewhere among the text so it's less obvious, but unfortunately, that didn't work out.

[Luckily, it's not even noticable in-game](http://i.imgur.com/o2zaE9k.png), so I guess that'll do for now. Even so, can't believe I missed something as big as this, I'm terribly sorry!
So far I haven't come across anything similar, but if I do stumble upon any other issues like these, I'll be sure to let you know immediately.

On another note, I also noticed three zoomed-in sprites (Gaap and Klauss) which I assume were added after my first sprite batch months ago, considering how blurry they are. I'm guessing these were literally just upscaled through whichever image editing software you guys might be using, and while it may get the job done, I believe tools like Waifu2x can provide much better results. I had previously used it to make the other zoomed sprites, so I did the same for these two.

You can find these revisions here : http://imgur.com/a/SYBTl
Again, I apologize for not noticing them sooner.

**Comment by ItaloKnox** [comment]
Sorry about that but I think imgur will make it difficult to fix the issue. First because imgur does compress the images, so that's not the ideal to get them for in-game use, and the second is that it completely kills the filenames.

If it's not much to ask for, can you upload these in a zip in their proper folders? I usually know where Higurashi images where, but my participation with Umineko was pretty minor, so I don't know where they're placed usually.

**Comment by Forteissimo** [comment]
Oh whoops, I had no idea Imgur did that to images. Sorry about that!
All the fixes are here inside their respective folders.

https://mega.nz/#!pIgCESIa!RFMqFmppPlg1ps_4uxly1kTZ8DHI_O3MiEL-DE21Yvc

**Comment by ItaloKnox** [comment]
Thanks a lot and sorry about that. I just pushed the new changes and they are already in the graphics patch.

I'll leave this issue open just in case you find something else.

**Comment by Forteissimo** [comment]
Thanks! I actually just happened to come across another one of these issues (Gaap vs George scene, with George's shield flashing once), so I'm assuming it's happening only to effects. Turns out having at least one pixel of transparency is enough to 'fix' these issues as opposed to cutting off an entire pixel, so I went ahead and did that to some non-transparent PS3 effects that might suffer the same risk, just in case.

https://mega.nz/#!cZJ0SY7T!CatZrR8svW7bHa6_wTarvM-kuRlT_RUU-iLJOvKC8O0

**Comment by ItaloKnox** [comment]
There you go, seems to be already uploaded and compiled. I'm going off for today but if you need anything else I'll be here tomorrow.

**Comment by Forteissimo** [comment]
https://mega.nz/#!QE4AkRQZ!8XDaWMwWKaH_mt-jQgi3JdgJ9-68u9cNvryPJ3T-XTo

Edited some very minor things that I thought could use a little polishing. Changes to the 0.utf (GC, weather and text position modifications), one of Jessica's sprites, a high res version of the Tsurupettan typography, character profile buttons that had yet to be updated, a widescreen version of the controls screen, and some of the time cards that were still using the old font. The credits' logos were also in black and white. Whether this was intended/necessary or not, I included color versions of the images anyway.

**Comment by ItaloKnox** [comment]
Looks like you did a fair amount of work there. Good job.

It's quite late here so I'll do the dirty work later today. I'll update here after I'm done. 
Thanks a lot!

**Comment by ItaloKnox** [comment]
Sorry about the delay, wasn't my intention to take this long to push the update. I think everything is in place right now, if you find anything wrong just tell me. 👍

**Comment by Forteissimo** [comment]
I was meaning to do something about the [weird perspective](http://i.imgur.com/NmDebQB.png) in ootsuki's scene and the sprite positioning [here](http://i.imgur.com/LhxWARF.png) and [here](http://i.imgur.com/41YMCNO.png). Can't believe I still forgot about fixing these before even though I kept reminding myself to do it. In case there happen to exist other scenes like the previous one, I cropped the sisters' sprites to the same dimensions as their original counterparts. If it's not much to ask for, would it be possible to add these files to the current release? Thank you.

https://mega.nz/#!VVxCDKqB!bSuGyBNVdhSW7xVBtRzGCYOqCaVsDN3jlIku38I-_5w

**Comment by Forteissimo** [comment]
@ItaloKnox While trying to fix the repeated background transitions at the beginning of Jessica's school festival scene I mistakenly commented off the first part's music as well. The 0.utf in the .zip file above should have it corrected. I'm really sorry about that.

Moreover, I noticed the .exe currently being used is [only ever so slightly blurry](http://i.imgur.com/r3KFMpC.png), so I made another one. It's not really even that noticeable in the first place, but still.

https://mega.nz/#!4ZJBRSYB!s81uq3yf9rS7iT3o4EypcWl1XxuH9FK6OPC7dMD5AqA

**Comment by ItaloKnox** [comment]
I just noticed you also left a comment a week ago and I didn't see it. Sorry about that, Higurashi notifications must have buried it.

I'm going to push these in the server right now, give me 30 minutes and it should be done. I'll reply here after I finish it.

**Comment by ItaloKnox** [comment]
There you go, 15 minutes earlier than I expected. As always, thanks a lot for doing so much for this patch. I'm amazed on how you can always find something else to fix, but maybe I'm being naive since I haven't done much in the Umineko side.

**Comment by Forteissimo** [comment]
https://mega.nz/#!8VoHXRga!r_LCKo0wBnn1OpFUk9v-MnEQs3r68jhHq66iMDtqVsc

I should've realized sooner that the positioning for the stakes' sprites had already been dealt with back when the script was modified for widescreen support with the old sprite batch. No wonder they appeared misplaced in certain scenes with the new sprites - my bad. I modified the dimensions and centered them once again to match the old sprites as to avoid any more of these mistakes. Again, I apologize.

Aside from that, there were a few event CGs/effects which hadn't been resized to a 1707x960 resolution. Whether this was intentional or not, I scaled them anyway. Some effects hadn't been changed to their PS3 counterparts, namely the blade from Ep. 3's fight and these bullet hole things. Also, In Ep. 1 there are certain parts where Maria's singing is heard after the phone call, so I added those in the script too.

Lastly, I edited the [interface ](https://i.imgur.com/zplOZhn.png)with the PS3's flower decoration in every element and [screen ](https://i.imgur.com/ky48MMQ.png) it's used. Just another small visual choice, but the bio buttons got their thick bevel effect again since that's really how they were in the beginning anyway, plus they look better that way. That and some higher quality logos for the splash screen.

**Comment by ItaloKnox** [comment]
Just got a chance to work on this. The server is a bit slow right now but I think the changes and the new release should go through in 30 minutes at least. As always I'm amazed by how you have an eye for details, and I honestly hope you'll be doing the same for Chiru.

**Comment by ItaloKnox** [comment]
I think everything should be uploaded now. As always, thanks a lot for putting your time into updating and fixing these issues.

**Comment by drojf** [comment]
Hey @Forteissimo, for Chiru I was thinking of making the resolution 1080p (instead of 960p it is now, eg the height wouldn't be same).  

Since I haven't worked with manually changing the GUI and effects, how difficult do you think it would be compared to going with the 960p? The main reason I initially went with 960p was because I thought it would be too much work to fix everything...

**Comment by Forteissimo** [comment]
That would be great! The interface would be fairly simple to recreate in a higher resolution, and other than the [repositioning of the elements in the menus](https://i.imgur.com/SAHKCUi.png), I don't believe it'd be too much of a hassle. The backgrounds, effects, and characters are obviously native to a 1080p resolution already, so it'd only be a matter of moving them over to this release. I was actually considering giving the current four episodes in 1080p a shot and had a .exe ready, but considering there a good amount of effects that'd need repositioning in the script and how I don't know every instance of those in-game, I gave it up for now.

**Comment by Forteissimo** [comment]
Thought I'd give it another try. It involved a lot more fiddling around the script than I imagined, but at the very least I've got some of the menus and the general 'gameplay' down for now. I'm amazed by how a slight change in resolution can make the game look so much better. I couldn't find the _exact_ font used for the interface, but I used Century Old Style Std, which is as close as it gets from all the fonts I searched.

![screenshot 2629](https://user-images.githubusercontent.com/20634116/31052021-707b5c64-a62d-11e7-87fa-ce0c3cb430aa.png)

![screenshot 2638](https://user-images.githubusercontent.com/20634116/31052033-b215a3b4-a62d-11e7-8521-cc8fb115d785.png)

![screenshot 2639](https://user-images.githubusercontent.com/20634116/31052043-0a1cd136-a62e-11e7-9c03-0b85f211a828.png)

![screenshot 2634](https://user-images.githubusercontent.com/20634116/31052105-79d8b6b0-a62f-11e7-8bf5-21b85353b0c4.png)


Still, I'm guessing things such as effects and other specific stuff like scrolling will be a bit more tedious to do, especially since there are so many of those out there.

**Comment by ItaloKnox** [comment]
That looks amazingly good. I played Umineko on PS3 back when it was released and this really throws me back. The games looks really, really good in fullscreen.

If I recall correctly we already use 1080p assets, right? What else would need adjustment other than UI and effects?

I wish the engine for Umineko was flexible like Unity is for Higurashi. Most of our work over there is automated, but the huge nature and the messy scripting really makes it hard to do here. I feel like I overlooked Umineko a bit too much, so if you are planning to give 1080p for the question arcs a shot, I'll do something to simplify things here. The current download methods are far from perfect and the release page is really confusing. I want to do some cleaning and a few changes but I need to be careful since every update that involves the graphics is huge and requires a new build, so I want this to be the last thing before we move on to Chiru.

**Comment by Forteissimo** [comment]
If I'm not mistaken, script-related modifications would only cover UI, effects and a number of certain scenes with specific character placement. I wouldn't know if there is more to that.

Pretty much all of the current assets are resized for the 960p resolution, but it'd only be a matter of bringing them over from the PS3 release's files and sorting them out.

It really would've been great if Umineko had received the same treatment as Higurashi since the engine does seem a whole lot more flexible and modern.

**Comment by ItaloKnox** [comment]
> Pretty much all of the current assets are resized for the 960p resolution

That's my biggest concern right now. The patch is already too big and it's a bother to update them (for the user), if we push 1080p it's going to get even worse. I have a few ways of circumventing that, first having Github handle the patch in 1gb parts (that's our cap) and then push additional monthly updates like we've been doing, but in separate parts. I also want to bring the Higurashi installer here. It's not a very modern thing but it works really well, and Umineko could definitely use this. It pretty much makes the process painless and avoids a number of issues we get.

As for the engine, it would definitely help a lot. The Higurashi patches are getting faster and faster, and now we are hacking the engine to put even more stuff in. One of my biggest wishes for Umineko would be to put lipsync in the game. I guess that's a stretch since we're already at the limit of the engine.

**Comment by drojf** [comment]
I think this is closed now.
