### ISSUE TITLE
The text overlay is jutting out to the left

### ISSUE THREAD

**Issue by Potestas777** [07th-mod/umineko-question#60]
Title pretty much says it. I only installed the voices, but not the graphics (the download link isn't working for me). Help is appreciated.
![image](https://cloud.githubusercontent.com/assets/28928962/26413168/1e2b08f4-40d1-11e7-9761-6e68a9f15b97.png)

**Comment by ItaloKnox** [comment]
You need to install the 0.utf file and replace the .exe as well, if you already didn't. Though the patch **is not** made with voices-only in mind. It'll break the game.

I just tried the download link for the graphics patch and it is working fine here. I'll add a mirror for the graphics and voices in a couple minutes, just in case.

**Comment by Potestas777** [comment]
I have installed the 0.utf file and replaced the exe as well. As for the voice only thing, I tried following the instructions described here: https://github.com/07th-mod/umineko-question/issues/11. Basically, I copied the utf code linked in that page. Appreciate you help a lot, thanks mate.

**Comment by ItaloKnox** [comment]
If you don't want to have the graphics, you don't need the new .exe and the 0.utf file you need is different (the one from the link you posted). That's why it's shifted.

But if you want the graphics, I have a mirror coming up in a few minutes. Just checking out the files, I'll update here with the link.

**Comment by Potestas777** [comment]
Ah, I see. Could you please link me to the 0.utf file I need? Thanks a lot for the assistance, and sorry for the trouble.

**Comment by ItaloKnox** [comment]
[It's here](https://github.com/07th-mod/umineko-question/blob/master/InDevelopment/ManualUpdatesVoiceOnly/0.utf). If you plan to add the graphics later I suggest you to not do it, the engine is pretty buggy and will break the game if you update it to support the graphics later.

**Comment by Potestas777** [comment]
I'll keep that in mind. I assume that if I want to add the graphics, uninstalling and reinstalling the game would work fine?

**Comment by ItaloKnox** [comment]
Not really, the issue lies in the save games. The engine snapshots the build and make the save from there, so if you update the game, the engine still loads the snapshot instead of the new script. If you start a new game it should be fine, though.

**Comment by Potestas777** [comment]
I understand now, thanks for clearing it up. I will try the new utf file and get back to you on how it turned out.

**Comment by Potestas777** [comment]
That seems to have fixed it. Thanks a lot for the help mate!
