### ISSUE TITLE
Ending scroll not synced with soundtrack

### ISSUE THREAD

**Issue by astone2007** [07th-mod/umineko-question#62]
Just got through playing the Steam version of EP1 using this mod for the first time and I noticed that the ending/credit images (both from the main EP1 ending and the EP1 Tea Party) were scrolling by very slowly, to the point that the ending music theme ended well before the image(s) reached the title shot at the very bottom, whereas I know that the original un-modded version had them synced up. I tried it on both my laptop and my PC (both a few years out of date, but easily capable of running Umineko), and once I applied the mod the endings went out of sync on both.

While it's not really a game-breaking issue, I was wondering if anyone else was having the game do something similar and/or if there was a known fix to get the timings matched up again. Thanks in advance.

**Comment by drojf** [comment]
The end credits scroll was definitely changed here FYI: https://github.com/07th-mod/umineko-question/issues/38 .

**Comment by drojf** [comment]
Can confirm it goes out of sync, at least for the ep3 scroll.

The current scroll function for ep3 is:
```
lsp bgsp,$witchh4,0,0
for %Free3 = 1 to 11479
	resettimer
	print 1
	msp bgsp,0,-1,0
	waittimer 10
	next
``
I should check how I fixed it on chiru and port the scroll functions.

**Comment by drojf** [comment]
on the 1080p branch (the main development branch now, soon to be merged with master), this has been fixed in: 

63025998b3b30555c356315b6f9ed3943f6a9979
4022085a2a9144d14056f883df58a31b1aa94693
1f1d134210fe8255f08e930f127ae6408ad047da
9392baac06af618ac12950d13714fcff2911f8d9
2faba2e3ea546bcafc9a7cd94b98cdf74481ed86
