### ISSUE TITLE
PS3 Background not working and no voice

### ISSUE THREAD

**Issue by roboticrobin** [07th-mod/umineko-question#63]
Hi guys, this is my first time posting on here so sorry if I make any mistakes. I feel like I'm missing a really obvious solution but I've looked everywhere.

Long story short, installed this back in January and have been playing it very, very slowly. Yesterday I encountered the glitch where the seven sisters won't leave the screen, and found that this had since been fixed and I just had to install the latest updates.

After doing that, I now have the issue that all the menus are shifted to the left. I originally had the issue that only the original backgrounds were being used so the game was playing in the incorrect resolution, but now the game is in fact in the correct resolution (from reinstalling the Umineko1to4.exe several times) but for some reason it's still using the original backgrounds and not the PS3 ones. The voices also aren't playing. 

I've uninstalled and reinstalled the game entirely and tried to apply the patch, and when it manages to get one thing right (ps3 sprites) two other things go wrong (backgrounds and voice not working).

Does anyone have any idea what I'm doing wrong here? Sorry if this would have been better posted in a different place.

**Comment by ItaloKnox** [comment]
Are you perhaps trying to load a save every time you try to fix the game? I think that might be the issue, the engine just doesn't work well when you update the game but the save is from the previous version.

**Comment by roboticrobin** [comment]
Not at all, whenever I test it out I start a new game the normal way....
I realise I have lots of broken things going on, so I may just have to give up and it's a bit silly asking for a solution vv
Here are some screenshots http://imgur.com/a/rEWMl

**Comment by ItaloKnox** [comment]
What really bothers me is that I can't help much. Even though I manage this project, I had very little participation in the patch process. Usually I'm in the Umineko side just to make sure everything is going smoothly.

I don't think this issue is impossible to fix, but something is indeed wrong. Maybe @drojf or @Forteissimo might be able to help you in this case, they had a lot more involvement in development. There's a chance this issue happened before.

**Comment by drojf** [comment]
It looks to me like you're using the wrong/the original script file (without the patched script file, everything will still be in 4:3 aspect ratio and shifted to the left. Try re-patching the script file.

If still not working, would be a good idea to check the backgrounds folder and the voices folder to see if there are actually files in there, and to check whether your folder paths are where you expect them to be (check out the downloads page for a expected folder paths). 

Probably re-installing from scratch would also fix this issue, that is freshly installing umineko, and then applying the latest patch.

**Comment by roboticrobin** [comment]
I had already uninstalled the whole game, reinstalled and then applied the patch. I'm not too sure which "script file" you mean though, does it have a different name? (My best guess is the 0.utf file)

I finally managed to fix all of it, not in the best way - I looked through the releases and found the one that was created for the specific fix for the original glitch I had, and then installed that onto a clean installed Umineko game. I know that I'm likely to face later glitches as I don't have the latest patch but this is the only way I've managed to make it work ;_;

This thread can be deleted if admins/mods prefer, I think my computer just hates me right now.... Thank you everyone for taking the time to help

**Comment by drojf** [comment]
just for reference, I'm assuming the one which didn't work was the latest (v2.8.5), but which version was the old version you used which did work?

**Comment by roboticrobin** [comment]
v2.8.5 didn't work, 2.0 was the version that did work. I was using the latest 0.utf when the game wasn't working properly, so possibly that's the cause?

**Comment by Forteissimo** [comment]
That's odd. Are you _absolutely_ certain you applied the patch correctly without missing any steps? Even if the old 0.utf file were still present as a backup, there's no reason it should be interfering with the latest script file. All of the voices and backgrounds are in their respective folders as well, so it really is strange.
I even reinstalled Umineko from scratch to check, applied the latest patch and everything worked as it should. I doubt it would make any difference, but maybe try deleting everything in the saves folder, the old 0.utf and arc.nsa?

**Comment by drojf** [comment]
I'm going to close this as you haven't responded for a very long time.
