### ISSUE TITLE
Voice pack unreadable/corrupted

### ISSUE THREAD

**Issue by Kalevispetke** [07th-mod/umineko-question#64]
Just joined to report this. The PS3 voices pack seems to be corrupted. I tried downloading twice and extracting with both 7-zip and classic winzip. Both are unable to extract further than the 05 folder on both occasions. 01-04 are fine but starting with 05 everything else is unreadable.

**Comment by ItaloKnox** [comment]
Hi,

I think this issue seems to be isolated to your machine. I just downloaded and tested the file:
```
7-Zip [64] 15.14 : Copyright (c) 1999-2015 Igor Pavlov : 2015-12-31
p7zip Version 15.14.1 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,32 CPUs x64)

Scanning the drive for archives:
1 file, 2154408860 bytes (2055 MiB)

Testing archive: umineko-voices-master-8f7a7e73e71f42e56295913705a9c5f785257cdc.zip
--
Path = umineko-voices-master-8f7a7e73e71f42e56295913705a9c5f785257cdc.zip
Type = zip
Physical Size = 2154408860
Comment = 8f7a7e73e71f42e56295913705a9c5f785257cdc

Everything is Ok

Folders: 49
Files: 51077
Size:       2295416658
Compressed: 2154408860
>>> elapsed time 33s
```

To not say that I can't help, I used our server to generate a temporary link for the file in case you still need to download it. [Download it here](https://transfer.sh/OCWm3/umineko-voices.zip). The file should be available for 14 days at least.

Don't forget to close the issue if your problem is solved. 👍

**Comment by Kalevispetke** [comment]
Ok, this was weird. I could actually also test okay with the same result but the pack still failed extraction. It claimed files are unreadable during extraction.

Then I copied the pack to an another hard drive and it worked! Everything extracted without a problem there. Looks like somethings up with my HDD. Thanks anyways. Game seems to work ok too!

**Comment by ItaloKnox** [comment]
Consider taking a look at your HDD using CrystalDisk. Should clear up any suspicions before it's too late.

Anyway, I'm glad you got it to work. :)

**Comment by Kalevispetke** [comment]
Yeah, umm I'm getting slightly short on space (15 GB left from 1TB) but the much larger graphics pack unpacked succesfully earlier.
