### ISSUE TITLE
No background when applying the voice only patch

### ISSUE THREAD

**Issue by farispie** [07th-mod/umineko-question#65]
Hello, all. I have applied the voice only patch (copying the voice files to the right place), and when I am reading, I do not get a background at all. The sprites and voices are there, but not the background. The background is completely black.

**Comment by ItaloKnox** [comment]
There's a chance you installed the wrong ``0.utf`` file. It should be [this one](https://github.com/07th-mod/umineko-question/raw/master/InDevelopment/ManualUpdatesVoiceOnly/0.utf).
