### ISSUE TITLE
voice only patch?

### ISSUE THREAD

**Issue by mistermoomoo** [07th-mod/umineko-question#67]
I'd like to read with original art + voices, is this possible?

**Comment by ItaloKnox** [comment]
Yes. Download the voices and [this file](https://github.com/07th-mod/umineko-question/raw/master/InDevelopment/ManualUpdatesVoiceOnly/0.utf). Beware that some issues might happen, we don't officially support this version of the patch.

Check the [latest release](https://github.com/07th-mod/umineko-question/releases/tag/v2.9.0) to get the link to the voice patch and see the installation instructions. Just skip the graphics part and downloading the .exe, you won't need it.

**Comment by mistermoomoo** [comment]
Thank you, it works perfectly!

**Comment by ItaloKnox** [comment]
Nice, I'm glad it worked. Have fun!
