### ISSUE TITLE
Corrupt file, graphics?

### ISSUE THREAD

**Issue by Nerikach** [07th-mod/umineko-question#70]
I just downloaded both voice and graphics files. The graphics file is 1,83GB and when I try to unzip it, it says te file is corrupt.
Can I use just the voice patch? The only part I want are voices anyway, so can the graphics patch be just skipped?

**Comment by ItaloKnox** [comment]
Hi, check the issue #67. This will help you set up the patch with voices only.

**Comment by Nerikach** [comment]
Hey, thanks! The comment is the issue says "download this file" and when I click on it, it's just a page with some text, not a file. Is it supposed tot be that way?

**Comment by ItaloKnox** [comment]
That's right, when you get the page with text only you should hit ``ctrl+s`` to save it as ``0.utf``. You should put this file inside the game folder (I recommend you to change to name of the old ``0.utf`` to something like ``old.utf``)

**Comment by drojf** [comment]
We shouldn't have this problem anymore with the new installer which verifies the zip file/redownloads parts of the zip which are corrupted.
