### ISSUE TITLE
Everything is shifted to the right

### ISSUE THREAD

**Issue by rurure21** [07th-mod/umineko-question#71]
How do I fix this? I can access the episodes but I cant see the thing. 

![image](https://user-images.githubusercontent.com/33855402/33056335-080cf230-cec0-11e7-9d01-e1c6e09fdf08.png)

**Comment by rurure21** [comment]
continued
![image](https://user-images.githubusercontent.com/33855402/33056372-3c910276-cec0-11e7-820f-b293ba2225b5.png)

**Comment by ItaloKnox** [comment]
Either you didn't download the .exe file needed to enable the widescreen mode or you didn't get the 0.utf file.

Check here and download the two files I mentioned by the end of the post: https://github.com/07th-mod/umineko-question/releases/latest

Also, how did you install the patch? Manually or using the new installer?

**Comment by Potestas777** [comment]
I have downloaded both of these files, but need help enabling the widescreen.

**Comment by drojf** [comment]
It has been nearly one year, I'm going to close this now.
