### ISSUE TITLE
Game closes after i start episode 1

### ISSUE THREAD

**Issue by Yasaka7** [07th-mod/umineko-question#72]
so i installed the patch manually and i also tried the installer. both times when i start the game and load episode 1 as soon as the doctor appears and want to say something, the game just closes. any solutions?

**Comment by ItaloKnox** [comment]
Can you please post the ``output_log`` file? Do a search for it inside the game folder.

**Comment by Yasaka7** [comment]
i dont find a output_log file. the only log i found is install.log.

**Comment by ItaloKnox** [comment]
Oops, sorry, I was on a run and for some reason thought this was the Higurashi repository.

Okay, do you know if the game is properly loading in widescreen and the new graphics are appearing? I would also suggest reinstalling the ``0.utf`` file. [Catch it here](https://github.com/07th-mod/umineko-question/releases/latest).

I'll have to dig some more information to pinpoint the issue, so sorry if this doesn't help much.

**Comment by Yasaka7** [comment]
somehow i got it to work properly. thanks for support.

**Comment by ItaloKnox** [comment]
That's good. Actually yes, [check here](https://github.com/07th-mod/umineko-answer/issues/1#issuecomment-346957747). I'm not really sure how it is done because I had little involvement with scripting, but in any case, you can ping DoctorDiablo to assist you if you can't make it work.

**Comment by ItaloKnox** [comment]
Oh, if you manage to get everything working, please let me know or close the issue. 👍

**Comment by Yasaka7** [comment]
that was helpful. i changed voicevol to 100 and the voices are louder now. is there also a way to lower the music a bit?

**Comment by drojf** [comment]
@DoctorDiablo has got something which can update the umineko 1-4 script so you can easily lower the volume but it's not yet applied to Umineko 1-4 (at least I think he hasn't done it yet). Once it's been applied it's quite easy to change the volume.

If it's a problem, I would wait until he's run applied his fix to Umineko 1-4.

**Comment by DoctorDiablo** [comment]
@Yasaka7 I just uploaded a fix for the volume issue, so you can download the latest [0.utf](https://github.com/07th-mod/umineko-question/raw/master/InDevelopment/ManualUpdates/0.utf) and drop that in your Umineko folder, and that should make the music a bit quieter.

@ItaloKnox Since I don't think there's anything else actively in development for the question arcs, would you like to package a release for this?

**Comment by Yasaka7** [comment]
@DoctorDiablo Thank you, but can you tell me the line where i can change music volume manually?

**Comment by DoctorDiablo** [comment]
@Yasaka7 Yeah, you can adjust it by changing volX and volY.  It's 3/4 right now, but you can change it to any fraction like 60/100 or whatever.

**Comment by ItaloKnox** [comment]
@DoctorDiablo I'll release it right now. Give me a couple minutes to set everything up, I'll need to rewrite the release now that we're using the wiki.
