### ISSUE TITLE
Voice-Only-Patch 0.utf provided in the guide/wiki didnt get the volume options changes from version 2.9.5

### ISSUE THREAD

**Issue by ZahnPastor** [07th-mod/umineko-question#73]
see title, the full graphics+voices patch has those options, they haven't been ported to the voice only option available on the wiki

**Comment by ZahnPastor** [comment]
looking at the voice-only 0.utf, it does support the option of controlling volumen, but in the latest release, the way the script handles volume changed, but the change hasnt been brought over to this version of the .utf

**Comment by ItaloKnox** [comment]
I think this is correct, I'll see if I can pass this along and fix it.

**Comment by DoctorDiablo** [comment]
Alright, I merged the volume change into the voice only version of the script.

You can grab the latest script [Here](https://raw.githubusercontent.com/07th-mod/umineko-question/master/InDevelopment/ManualUpdatesVoiceOnly/0.utf).  Dropping the new script in will probably mess up your saves.  I think it'll just set you a few lines back and you can continue from there.
