### ISSUE TITLE
The Application "Umineko1to4" can't be opened.

### ISSUE THREAD

**Issue by InochiPM** [07th-mod/umineko-question#74]
I followed the instructions on how to manually install all of the files and everything but when i got to launch the game i get this error, it seems to the be umineko4 file that throws it into broken. when i replace it with the backup i have it works but the whole menu is shifted because of the umineko4 file isn't correctly formatted. I also noticed that the umineko file inside in openable wit the terminal but the new one isnt and tries to open in texteditor maybe the formatting is wrong? 
<img width="1680" alt="screen shot 2017-12-14 at 11 08 32 pm" src="https://user-images.githubusercontent.com/13459080/34026393-bef5cd30-e123-11e7-8651-a352fa119234.png">

**Comment by ItaloKnox** [comment]
Hello, [this should help you fix the issue](https://github.com/07th-mod/umineko-question/issues/56#issuecomment-284396896). If it works for you I'll push an update to make sure no one have this issue again. :)

**Comment by InochiPM** [comment]
Awesome its working now!

**Comment by ItaloKnox** [comment]
Great, I'm pushing the update to the wiki. Next time that won't happen. 👍
