### ISSUE TITLE
Background for chapel has transparent windows

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-question#76]
https://user-images.githubusercontent.com/1249449/34504478-f6eb5a4e-f072-11e7-910a-bb5c6ebedbaa.png

The chapel images were missing their background for the windows.

Attached below is a hotfix to fix that image. I also noticed the image wasn't resized at all...it was just the raw ps3 image. Probably my fault since I did the final pass on the backgrounds.

[chapel_background_hotfix.zip](https://github.com/07th-mod/umineko-question/files/1599041/chapel_background_hotfix.zip)

**Comment by ItaloKnox** [comment]
I got those added to the resources and added them to the installer. I'll also add them to the wiki since it affects everyone. Close this for me if I'm not forgetting anything.

**Comment by drojf** [comment]
yea I think that's it, thanks
