### ISSUE TITLE
Question arc 1-4 installer issue

### ISSUE THREAD

**Issue by mikem2567** [07th-mod/umineko-question#77]
Hi there, I recently installed the patch for umineko and the voices, backgrounds, cgs, and menus are all missing, is there a step after installing? I used the automatic ep 1-4 version and all that's changed is the character sprites. Do I have to delete previous saves?

**Comment by ItaloKnox** [comment]
Hi! Did you try starting a new game to see if it works better? Can you also post a screenshot of your game folder?

**Comment by mikem2567** [comment]
![untitled](https://user-images.githubusercontent.com/35643149/35189879-25cd515c-fe22-11e7-9749-a19827c38502.png)
![untitled2](https://user-images.githubusercontent.com/35643149/35189880-25d8b4de-fe22-11e7-98a9-3646fa05124f.png)
I;m not sure if the files uploaded but what's happening is I'm getting the old backgrounds with the new character sprites, I had it working for a second in new game mode but didn't have the ability to save my progress it would just revert back to the main menu when I would try to save.

**Comment by ItaloKnox** [comment]
Yeah, that's definitely not normal. Your game folder looks normal, so I'm clueless about what we can try. I'm going to ping @drojf and @DoctorDiablo so they can take a look at this. They might have a better suggestion.

**Comment by mikem2567** [comment]
okay thank you for the help anyways

**Comment by drojf** [comment]
from the screenshot it looks like 
- your .exe file hasn't been patched (window isn't 16:9)
- your script file hasn't been patched (text would be off-screen with the new script file)
- your background images are missing (i can see the old backgrounds)

but i'm not really sure...I wonder if steam tried to update your game or something and overwrote some files...for a start I would try manually downloading the script file and the patched .exe file and seeing if that makes any difference.

Scroll down to "manual installation" here: https://github.com/07th-mod/guide/wiki/Umineko-Part-1---Voice-and-Graphics-Patch , and download the 'patch' and 'executable' and follow the instructions.

**Comment by mikem2567** [comment]
One thing I don't get is I have all of the new backgrounds in the bmp folder is there a way to add them to the game? I don't care much about the voices just the backgrounds and character sprites. 

If I update manually it would only be the script file and the .exe file not the voices and graphics  right?

**Comment by drojf** [comment]
yea, only those two parts. You should have got the rest of the stuff from the automated installer 

As long as the files are in the right path, the game will automatically load them. I thought you used the manual installer though, which should place them in the right path. 

But yea, can you open one of the background directory and take a screenshot which shows the path in windows explorer? Then I can check it's in the right place

**Comment by drojf** [comment]
Not sure if you're still there, but we updated the install script to be more robust. if you make sure all the big files are in the main folder, the script should verify /repair them if necessary. It will also tell you if you're in the wrong folder/if there are any errors during extracting etc.

**Comment by drojf** [comment]
Since the automatic installer has improved since this issue was posted, I think I can close this issue. If @mikem2567 is still having problems you can reopen this issue.
