### ISSUE TITLE
ADV style textbox?

### ISSUE THREAD

**Issue by Eisen-S** [07th-mod/umineko-question#80]
I was able to install the latest patch via manual installation for both arcs. Was just going to ask if there's any way to have the text on the lower side of the screen with the name of the one speaking and not occupying the entire screen. I tried searching but could not understand how the others did it.

**Comment by ItaloKnox** [comment]
It's currently in development for the Answer Arcs. I'm unsure if it's going to be ported over to the question arcs but it's a possibility. Check this [issue](https://github.com/07th-mod/umineko-answer/issues/12) for more information.
