### ISSUE TITLE
Sprites/Voices/Backgrounds back to unpatched Version after Steam Update

### ISSUE THREAD

**Issue by Saile9** [07th-mod/umineko-question#81]
Hello,
after Steam updated the game, the game is back to "normal" without any sprites/voices and so on. Do I have to uninstall the patch and reinstall it again or what do I need to do?
Thanks in advance!

**Comment by ItaloKnox** [comment]
Hi! All you need to do is to download the newest script from the repository. https://github.com/07th-mod/umineko-question/raw/master/InDevelopment/ManualUpdates/0.utf

**Comment by Saile9** [comment]
Thanks for the quick answer!
But how do I do that? Sorry for the dumb questions. I really have no idea about this stuff.

**Comment by ItaloKnox** [comment]
Just right click the link I sent above and select "save link as..." and put the file in your game folder. Overwrite when asked and you're ready to go.

**Comment by Saile9** [comment]
Worked out perfectly.
Once again thank you!
