### ISSUE TITLE
STEAM UPDATE PROBLEMS 17-02-18 SEE HERE

### ISSUE THREAD

**Issue by Cyuss321** [07th-mod/umineko-question#82]
Seems like it broke the patch, the graphics and backgrounds are all messed up. I was on the last chapter too hoping to finish this soon. Is there any fix coming soon for this? I've tried reinstalling it several times but keep getting the same issues. I'm guessing the answer arcs is probably going to have the same problems since it also got an update today.

EDIT: Nevermind, apparently deleting the game entirely and redownloading it off steam and then running the patch again will fix it. I guess if anyone else has this issue they'll know how to fix it here at least.

**Comment by drojf** [comment]
For anyone who has the same issue, this should fix your game enough so you can play it:

- Re-download 0.utf and the .exe file, copy to your game folder (replace existing).
- I suspect steam may also replace the opening movies so they revert to the old ones. If you can live with that, you don't need to re-download it.

I believe steam only touches files which were originally there, and the files listed above are the main ones.

I'll leave this issue open for others to see - if you close it it's hidden by default on github.

**Comment by ItaloKnox** [comment]
I'll link this on the wiki just in case.

**Comment by drojf** [comment]
The updates to the .exe/save files should prevent this issue from happening.
