### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by weeaboo-123737** [07th-mod/umineko-question#84]
I was wondering if there were any plans to add Linux support for this patch now that they've added an official [executable](https://github.com/07th-mod/umineko-question/files/1733259/Umineko1to4.zip).

[Patch changelog here.](https://steamcommunity.com/games/406550/announcements/detail/3026853150303409814)

**Comment by ItaloKnox** [comment]
Actually yes, it should take a couple more days but we will add support for Linux.

**Comment by drojf** [comment]
Try this patched executable (I haven't tested it but hopefully it will just work)

[widescreen-Umineko1to4.zip](https://github.com/07th-mod/umineko-question/files/1733365/widescreen-Umineko1to4.zip)

**Comment by weeaboo-123737** [comment]
@drojf Great, that works. Thanks!

Unfortunately I don't have 5to8 so can't provide the executable.

**Comment by drojf** [comment]
Someone sent me the 5to8 exe - the 1080p patch worked OK, but the patch which makes the videos fullscreen didn't work. Will have to investigate some time to fix that.

**Comment by drojf** [comment]
Actually wasn't bad as I thought - just had to ignore the first match in the executable. I think this should work. **To test that this works properly**, you need to watch at least one video in the game and check it doesn't crash (such as the opening video)

[Umineko5to8w_video.zip](https://github.com/07th-mod/umineko-question/files/1734237/Umineko5to8w_video.zip)

**Comment by drojf** [comment]
OK, the discord guy confirmed it was working, so I added the two .exes to the manual install instructions here: https://github.com/07th-mod/guide/wiki/Umineko-Part-1---Voice-and-Graphics-Patch
