### ISSUE TITLE
Missing Alternate Clothes sprite for Maria

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-question#93]
It was reported on discord that sprites do no appear during maria's flashback. During the flashback, maria and rosa are meant to appear with different clothes. This is set with a function which rebinds the sprite filenames as shown:

```
gosub *MAR_Isyou3  ;TODO: change to alt outfits
gosub *ROS_Isyou2
```

```
*MAR_Isyou3    ;魔女マリア

mov $MAR_DefA1,"bmp\TATI\MAR\3\MAR_DefA1"          ;真里亞立ち絵デフォ
mov $MAR_DefA1k,"bmp\TATI\MAR\3\MAR_DefA1k"          ;デフォ影
mov $MAR_WaraiA1,"bmp\TATI\MAR\3\MAR_WaraiA1"          ;笑い
mov $MAR_AkuwaraiA1,"bmp\TATI\MAR\3\MAR_AkuwaraiA1"          ;悪笑い
mov $MAR_IkariA1,"bmp\TATI\MAR\3\MAR_IkariA1"          ;怒り
mov $MAR_KomaruA1,"bmp\TATI\MAR\3\MAR_KomaruA1"          ;困る
mov $MAR_OdorokiA1,"bmp\TATI\MAR\3\MAR_OdorokiA1"          ;驚き
mov $MAR_MajimeA1,"bmp\TATI\MAR\3\MAR_MajimeA1"          ;真面目
mov $MAR_NakuA1,"bmp\TATI\MAR\3\MAR_NakuA1"          ;泣く
;mov $MAR_DefA2,"bmp\TATI\MAR\3\MAR_DefA2"
;mov $MAR_Kuro_DefA1,"bmp\TATI\MAR\3\MAR_Kuro_DefA1"          ;黒真里亞立ち絵デフォ
;mov $MAR_Kuro_WaraiA1,"bmp\TATI\MAR\3\MAR_Kuro_WaraiA1"          ;黒真里亞笑い
mov $MAR_AkuwaraiA2,"bmp\TATI\MAR\3\MAR_AkuwaraiA2"          ;悪笑い２
mov $MAR_AkuwaraiA3,"bmp\TATI\MAR\3\MAR_AkuwaraiA3"          ;悪笑い３
mov $MAR_WaraiA2,"bmp\TATI\MAR\3\MAR_WaraiA2"          ;笑い２
mov $MAR_NiyariA1,"bmp\TATI\MAR\3\MAR_niyariA1"          ;ニヤリ
mov $MAR_NiyariA2,"bmp\TATI\MAR\3\MAR_niyariA2"          ;ニヤリ２
mov $MAR_fukigenA1,"bmp\TATI\MAR\3\MAR_fukigenA1"          ;不機嫌
mov $MAR_fukigenA2,"bmp\TATI\MAR\3\MAR_fukigenA2"          ;不機嫌２
mov $MAR_SakebuA1,"bmp\TATI\MAR\3\MAR_SakebuA1"          ;叫ぶ

return
```

However, the folder `MAR\3` is missing from the graphics patch. I'm not sure if other folders are missing too - this will have to be checked.

The end result of this is that the sprite is not displayed at all. You think "but it should display the original game sprites, and load them from the .arc file" - BUT YOU'RE WRONG. 

So I go and check the game sprites, and the sprites are not there - there is no `3` folder for Maria. I then check the original game script, and there is no *MAR_Isyou3 function

So basically I think maria's clothes switching was ported from the umitweak script, but the sprites weren't added/forgot to be added (from the ` ;TODO: change to alt outfits` comment).

~For now we can either:~
~Although I'll admit in that scene it looks weird because maria's outfit is unreasonable for that scene. So perhaps better to leave it as is for now, until we generate the clothes switched sprites.~

EDIT3: actually it shouldn't be too hard to fix up. will just fix it

I believe @ReitoKanzaki did the changes relating to this particular issue. If you're still around, does this fix (just putting in the new sprites) sound reasonable?

EDIT2: ctom checked for me just now  - The Umitweak release didn't have these folders either (ros2 and mar3).  So I can understand why the folder(s) are missing.
EDIT4: someone else reported the newer umitweak release has the folders included...and alternate sprites for jessica etc.

**Comment by drojf** [comment]
Here are the alternate sprites for Maria and Rosa

[Maria Rosa Alternate Sprites.zip](https://github.com/07th-mod/umineko-question/files/1801134/Maria.Rosa.Alternate.Sprites.zip)

The only known missing alternate sprites at the moment is Jessica's school sprites. But at the moment her 'default' sprites are shown instead of the alternate sprites.

**Comment by ReitoKanzaki** [comment]
Sprites should work as soon as the images are placed in the /3/ folders. Jessica's sprite, I believe was manually coded.

**Comment by drojf** [comment]
Cool, just wanted to know if there were any gotchas to be wary of. I tested the maria/rosa sprites and they seemed to work fine, not sure about jessica's sprites.

**Comment by drojf** [comment]
This should be fixed as of 13-04-18 when the graphics pack was updated. (reminder - no script changes were made, only maria's and rosa's sprite folders were updated)
