### ISSUE TITLE
widescreen issue

### ISSUE THREAD

**Issue by urgoodfriend** [07th-mod/umineko-question#94]
Since the last steam uptade, I can't play in widescreen wich is annoying because i don't see the end of the sentence so is there any way to fix it?
Also i have already fix the ps3 patch issue relied to steam uptade.

**Comment by drojf** [comment]
> Also i have already fix the ps3 patch issue relied to steam uptade.

I assume you mean you already followed the instructions here?: https://github.com/07th-mod/umineko-question#warning---steam-updates

Could you take a screenshot of your screen so I can see what it looks like?

I'm guessing you don't have the right .exe file, and you need this exe file to make it widescreen: https://github.com/07th-mod/resources/releases/download/Beato/Umineko1to4.exe

**Comment by urgoodfriend** [comment]
![capture](https://user-images.githubusercontent.com/37309955/37328984-e002d076-2693-11e8-9ed6-464856e7629b.JPG)

**Comment by urgoodfriend** [comment]
so i recorded the .exe so now in my umineko folders i have the .exe  8153 ko version with the 0.utf : 11742ko version and it seems to work perfectly. But if i'm not wrong the latest 0.utf version was the 14989ko version so we can basically play with the old 0.utf? Just changing the .exe. Maybe i'm completely wrong but anyway it's works now.

**Comment by urgoodfriend** [comment]
and also ty for helping me

**Comment by drojf** [comment]
The new .exe launches the file called '0.u' instead of '0.utf' (so that if steam overwrites '0.utf', the game still runs properly). Therefore, you should look at the '0.u' file if you want to compare them by file size that you have the right one.
