### ISSUE TITLE
Wrongly translated dialogue (dialogue and text mismatch)

### ISSUE THREAD

**Issue by newby24** [07th-mod/umineko-question#95]
In this scene from episode 2, Kanon clearly says "Nee-sama" yet, the dialogue says "Nee-san"
![neesama jpg](https://user-images.githubusercontent.com/36610110/37898934-627151a8-30ea-11e8-8fe7-9783985e49d0.png)

The same thing happens later on in the episode. "The characters do not say "Krauss-sama" like indicated with the text:
![notkrauss-sama-danna sama](https://user-images.githubusercontent.com/36610110/37898971-7c0c872c-30ea-11e8-8fcb-d1c24e04351c.jpg)

**Comment by ZahnPastor** [comment]
i dont think this is much of a bug in terms of the patch, but its just apparently a translators decision that was made by mangagamer/witch hunt

**Comment by drojf** [comment]
I'm going to close this for now. I'm not sure about modifying the translation to match the voices, and if we were to do so, we'd essentially need to play the entire game to fix it.
