### ISSUE TITLE
Sound gone at ep 2

### ISSUE THREAD

**Issue by Lynnlen** [07th-mod/umineko-question#98]
I am currently playing ep 2 but while playing it I lost all the sound and can't get it back. I tried closing game and restarting my computer, can someone help me.

[Update] when I increase the volume on the voices, the test voice will appear just for a second, this seems to happen when repeatable press the voice + or - button. It does not work for the music volume and only works when you increase or decrease the voice volume. The test voice will still play so long as you keep play even after reaching the max on the volume.

**Comment by drojf** [comment]
Try pressing the 'M' key (mute button) on your keyboard.

This is just part of the engine, not our doing. Perhaps I should add this to the FAQ/troubleshooting of the installer (this has happened many times, including to myself lol).

Also, you might wanna check out the full list of keyboard commands from the main menu before you continue playing.

If this doesn't fix the problem ... not sure what it is but i'll look into it further.

**Comment by Lynnlen** [comment]
Thank you it did indeed fix it.

**Comment by drojf** [comment]
OK i added a note to the 'troubleshooting' section of the installer. enjoy the game :)
